### ISSUE TITLE
Unreachable code after infinte loop inside generic function "http#serve"

### ISSUE THREAD

**Issue by MaxGraey** [denoland/deno_std#142]
Code in this [line](https://github.com/denoland/deno_std/blob/master/http/http.ts#L86) never run and listener never closing.

**Comment by kevinkassimo** [comment]
Currently there is indeed no way of closing the listener. It would be a good idea to revamp the HTTP module with more careful design (and possibly emulating part of implementation from Go) (a few contributors have expressed interest on this)

**Comment by sholladay** [comment]
Yep, I was looking for a way to implement a [server.close()](https://nodejs.org/api/http.html#http_server_close_callback) equivalent in [pogo](https://github.com/sholladay/pogo), order to gracefully stop accepting requests and exit the process with a zero exit status. This is needed for production deployments.

**Comment by kevinkassimo** [comment]
For people who want this feature immediately, it is possible to add `server.close` feature given current `http.ts` structure. Basically you want to add something so that you can call and stops
https://github.com/denoland/deno_std/blob/bef7ba14303997a05cdd1ea0d28ffefeee75c993/http/http.ts#L60-L69
(this piece of code immediately tries to wait for a next `accept` when the previous one is handled)
and also breaks from
https://github.com/denoland/deno_std/blob/bef7ba14303997a05cdd1ea0d28ffefeee75c993/http/http.ts#L74-L85
(This is for sure not an elegant structure. I hope someone could take some time to improve this while still keeping the capability of doing async iterator for request handling.)

**Comment by JoakimCh** [comment]
I'm testing a hack to support closing the server, preferably something with very few and simple changes.

For example this is a way you could run the server and handle it closing:
```typescript
const generatorStopper = {stop: null}
const requestGenerator = http.serve(this.address, generatorStopper)

for await (const req of requestGenerator) {
  if (req === false) {
    log('Server has closed')
    break
  }
  // else handle the request
}
```
Where this would be called to stop it:
```javascript
generatorStopper.stop()
```
And how the serve generator function could implement it (not finished, but works). I'm no TypeScript programmer, so please excuse my dirty JavaScript... :P 
```typescript
export async function* serve(addr: string, generatorStopper) {
  const listener = listen("tcp", addr);
  const env: ServeEnv = {
    reqQueue: [], // in case multiple promises are ready
    serveDeferred: deferred()
  };

  // Routine that keeps calling accept
  let handleConn = (_conn: Conn) => {};
  let scheduleAccept = () => {};
  const acceptRoutine = () => {
    scheduleAccept = () => {
      listener.accept().then(handleConn);
    };
    handleConn = (conn: Conn) => {
      serveConn(env, conn); // don't block
      scheduleAccept(); // schedule next accept
    };

    scheduleAccept();
  };

  acceptRoutine();
  
  if (typeof generatorStopper == 'object' && 'stop' in generatorStopper) {
    generatorStopper.stop = (() => {
      env.serveDeferred.resolve(false);
    });
  }
  
  // Loop hack to allow yield (yield won't work in callbacks)
  while (true) {
    if (await env.serveDeferred.promise === false) {
      break
    }
    env.serveDeferred = deferred(); // use a new deferred
    let queueToProcess = env.reqQueue;
    env.reqQueue = [];
    for (const result of queueToProcess) {
      yield result;
      // Continue read more from conn when user is done with the current req
      // Moving this here makes it easier to manage
      serveConn(env, result.conn, result.r);
    }
  }
  listener.close();
  yield false;
}
```
Of course I modified a few other places in the code to support the new "false" type. E.g:
```typescript
interface Deferred {
  promise: Promise<{}>;
  resolve: (arg) => void;
  reject: () => void;
}
```
And the `listenAndServe` function needs to be modified also, or just commented away.

If doing something like this then we need a way to handle "Uncaught Other: Listener has been closed". I have not tried to solve everything yet... I've just spent a few minutes at this! And if we need to connect to our own server for the socket.accept() function to stop holding, then that's an easy hack to fix that...

All I'm saying is that there are solutions to implement a way to close the server and it is not hard to do. But since I'm no TypeScript programmer I'm not really going to contribute with any pull requests any time soon, I don't have the energy/health to get involved in this yet.
