### ISSUE TITLE
std/node "EventTarget" is incompatible with global "EventTarget"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1455]
Currently in `node/events_test.ts` there are some tests that use `EventTarget` from the global scope, however Node's implementation of `EventTarget` is different that one coming from DOM: https://nodejs.org/api/events.html#eventtarget-and-event-api

```
$ node
Welcome to Node.js v16.11.1.
Type ".help" for more information.
> EventTarget
[class EventTarget] { [Symbol(nodejs.event_target)]: true }
>
```

**Comment by bartlomieju** [comment]
So "events" implementation was reworked in #1558; we still need to fix situation with `EventTarget` - that said I think it will be quite hard as Deno's and Node's global `EventTarget` are incompatible.

**Comment by lucacasonato** [comment]
As for:

> 1. Whereas DOM EventTarget instances may be hierarchical, there is no concept of hierarchy and event propagation in Node.js. That is, an event dispatched to an EventTarget does not propagate through a hierarchy of nested target objects that may each have their own set of handlers for the event.

We have the same behaviour as node, because we also don't have a hierarchy. This should not be an issue.

> In the Node.js EventTarget, if an event listener is an async function or returns a Promise, and the returned Promise rejects, the rejection is automatically captured and handled the same way as a listener that throws synchronously (see EventTarget error handling for details).

This is just a dumb deviation from Web APIs. Why did anyone think this was ok? It breaks the entire model for event handlers... we should not implement this. Any Node code that uses this behaviour should be considered buggy (as it won't work in browsers), and should fix their code to not rely on this. It breaks the entire internal propagation and `preventDefault` handling if event targets handle errors asynchronously... we only need to get 80% there, right?

**Comment by piscisaureus** [comment]
Discussed off-github: although this issue exists, it is unlikely to cause any problems and we won't address it for now.
If anyone discovers an real world bug that is caused by this issue, feel free to open a new issue.
