### ISSUE TITLE
Is deno supports runtime type checking?

### ISSUE THREAD

**Issue by NarHakobyan** [denoland/deno_std#151]

**Comment by kitsonk** [comment]
This really isn't a question for `std` and is more appropriate for deonland/deno.  The short answer is no, and it never will.

The longer answer is that because Deno has the TypeScript compiler built into it, type safety is checked before any code is run.  Then plan for the future is to restore that checking for plain JavaScript files too.  So from a developers perspective, it is effectively runtime type safety as the source code that is authored is typed checked.  There isn't a logical use case where actual runtime type checking would benefit anyone and would only be a runtime performance overhead.

**Comment by NarHakobyan** [comment]
thanks @kitsonk

**Comment by paperbenni** [comment]
If all type checking is gone once the code is actually running, wouldn't that still leave possible runtime errors like invalid data received over the network or invalid casting?
