### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by akircher** [denoland/deno_std#153]
Forgive me if this is already been discussed or I am wrong, but is there a reason that Deno HTTP (and Websockets) are based on HTTP/1.  Everything else in Deno seems so modern, it seems weird to support the old standard and not HTTP/2.  Maybe this is already on the roadmap?

Obviously biased article supporting this viewpoint:
https://medium.com/@pgjones/http-1-should-die-81b7588d617e

**Comment by ry** [comment]
We are slightly in limbo regarding the HTTP server. Currently we have this one implemented in TypeScript but it's slow. [I have attempted to build a native version which would use Rust's HTTP/2 libs ](https://github.com/denoland/deno/pull/1147) but due to [technical reasons] it was not fast enough.

I am currently optimistic that the [TypeScript HTTP server ](https://github.com/denoland/deno_std/blob/master/http/http.ts) can be made fast. We think our bottleneck is in the central way that Deno sends and receives messages to V8 (the "calling convention"). @piscisaureus is actively working on a new version of this - we should have an idea soon (~1-2 weeks) if the current TypeScript implementation will be fast enough or if we need to go to native Rust again.

Once we understand these performance problems better, we will either attempt to implement HTTP/2 in TypeScript or we will return to using Rust's Hyper which already supports it.

[We are also interested in implementing the ability to use QUIC.](https://github.com/denoland/deno/issues/1558)  But that is a ways off still.

**Comment by akircher** [comment]
Thanks for the detailed and thoughtful response!  For HTTP/3 and QUIC in RUST this library looks interesting
https://blog.cloudflare.com/enjoy-a-slice-of-quic-and-rust/
