### ISSUE TITLE
assertEquals 

### ISSUE THREAD

**Issue by shivam-tripathi** [denoland/deno_std#1777]
**Describe the bug**
-0 and 0 are not same

**Steps to Reproduce**

```ts
import { assertEquals } from "https://deno.land/std@0.119.0/testing/asserts.ts";
Deno.test({
  name: "zero and negative zero",
  fn: () => {
    assertEquals(0, -0);
  },
});

```

**Expected behavior**

`-0 == 0` and `-0 === 0` gives true always.

**Environment**

- deno version: `deno 1.17.1 (release, x86_64-apple-darwin)`
- std version: `0.119.0`

**Comment by lmx-Hexagram** [comment]
According to [MDN Strict equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality#description) `Numbers must have the same numeric values. +0 and -0 are considered to be the same value.`. I think this is a bug, so I open a PR.

**Comment by shivam-tripathi** [comment]
What about lists with numbers? ['hello', 0, 23.45] and  ['hello', -0, 23.45] are still not equal. Similarly for objects etc.

**Comment by lmx-Hexagram** [comment]
Also on object {test:0} and {test:-0}. Let me think about it.

**Comment by lmx-Hexagram** [comment]
Sorry for my late reply. 
Case like `assertEquals([-0], [0])` and `assertEquals({test:0}, {test:-0})` will success after this PR.
Because 
1. `assertEquals` call `equal`
2. `equal` will Iterating over elements on two objects(array is object)
3. By Recursive `compare` each elements 
4. When meet two number this PR will deal `-0` and `+0` and `0` as the same value.
