### ISSUE TITLE
node(events): add internal/event_target (or equivalent)

### ISSUE THREAD

**Issue by Nautigsam** [denoland/deno_std#1865]
Currently `node/_events.js` uses `require("internal/event_target")` but this file does not exist.
https://github.com/denoland/deno_std/blob/1c8e6ce506267edb3ce64ce667d9611161b35a42/node/_events.js#L790-L815
This function is used in several places e.g. tests copied from Node.js source. In order to convert it to static imports, we need to get this file from Node or wrap Deno's `EventTarget` and `EventEmitter`.

**Comment by samthecodingman** [comment]
I currently manually patch this bug out with a **dodgy** polyfill that walks the prototype chain to find the [local enumerable `Symbol()`](https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/ext/web/02_event.js#L843-L882) defined on Deno's built-in `EventTarget` (since [22 Sep 2021](https://github.com/denoland/deno/pull/12166)).

**Disclaimer:** This is very much a hack to push discussion forward on building an actual solution. **Use at your own risk.**

The lines referenced here are as they originally appear in [`std/node/_events.mjs`](https://github.com/denoland/deno_std/blob/59d2158966649b7aa3a2eb3025a163e98c1c2312/node/_events.mjs). If you want to replicate these mutations, you will want to start from the bottom up, which is the order I will list them.

Replace [lines 796-810](https://github.com/denoland/deno_std/blob/59d2158966649b7aa3a2eb3025a163e98c1c2312/node/_events.mjs#L796-L810):
```js
// Require event target lazily to avoid always loading it
const { isEventTarget, kEvents } = require("internal/event_target");
if (isEventTarget(emitterOrTarget)) {
  const root = emitterOrTarget[kEvents].get(type);
  const listeners = [];
  let handler = root?.next;
  while (handler?.listener !== undefined) {
    const listener = handler.listener?.deref
      ? handler.listener.deref()
      : handler.listener;
    listeners.push(listener);
    handler = handler.next;
  }
  return listeners;
}
```
with:
```
if (isEventTarget(emitterOrTarget)) {
  return getEventTargetListeners(emitterOrTarget, type);
}
```

Remove [lines 152-155](https://github.com/denoland/deno_std/blob/59d2158966649b7aa3a2eb3025a163e98c1c2312/node/_events.mjs#L152-L155):
```js
if (isEventTarget === undefined) {
  isEventTarget = require("internal/event_target").isEventTarget;
}
```

Replace [line 98](https://github.com/denoland/deno_std/blob/59d2158966649b7aa3a2eb3025a163e98c1c2312/node/_events.mjs#L98):
```js
let isEventTarget;
```
with:
```js
function isEventTarget(obj) {
  const proto     = Object.getPrototypeOf(obj);
  const parentIs  = (proto) ? isEventTarget(proto) : false;
  return parentIs || (obj.constructor && obj.constructor.name === "EventTarget" && Object.getOwnPropertySymbols(obj).some(s => s.toString() === "Symbol()" && obj[s] && obj[s].listeners));
}
function getEventTargetListeners(obj, type) {
  const proto     = Object.getPrototypeOf(obj);
  const inherited = (proto) ? getEventTargetListeners(proto, type) : [];
  if (inherited.length > 0) return inherited;
  // eventTargetData is either undefined or obj[Symbol()] where that object has a truthy listeners property and obj is a "EventTarget" object.
  const eventTargetData = (obj.constructor && obj.constructor.name === "EventTarget" && Object.getOwnPropertySymbols(obj).filter(s => s.toString() === "Symbol()" && obj[s] && obj[s].listeners).map(s => obj[s])[0];
  // eventTargetData.listeners[type] is a ({ callback: Function, options: AddEventListenerOptions })[]
  return eventTargetData?.listeners.[type]?.map(listener => listener.callback) || [];
}
```
The above recursion methods are based on this [prototype search](https://stackoverflow.com/a/55006988/3068190) by [Josh Klodnicki](https://stackoverflow.com/users/8882017). The symbol being found here is likely meant to be hidden, but because it's there, may as well use it until proper support is implemented to export the symbol or access the event listeners some other way.

A potential 'proper' approach could be to expose [`getListeners()`](https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/ext/web/02_event.js#L861-L863) on `window.__bootstrap.eventTarget` in `denoland/deno/ext/web/02_event.js` like so:
```js
window.__bootstrap.eventTarget = {
  EventTarget,
  setEventTargetData,
  getListeners
};
```
Allowing for usage here similar to:
```js
const isEventTarget = (obj) => Object.getPrototypeOf(window.__bootstrap.eventTarget.getListeners(obj))===null;
const getEventTargetListeners = (obj, type) => window.__bootstrap.eventTarget.getListeners(obj)?.[type]?.map(listener => listener.callback) || [];
```
