### ISSUE TITLE
TypeScript errors with "noImplicitAny: false"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1868]
```
error: TS2345 [ERROR]: Argument of type 'T' is not assignable to parameter of type 'never'. common.push(A[reverse ? A.length - i - 1 : i]); ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:32:19

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.123.0/testing/_diff.ts").DiffType' is not assignable to type 'never'. Type 'import("https://deno.land/std@0.123.0/testing/_diff.ts").DiffType' is not assignable to type 'never'. type: swapped ? DiffType.removed : DiffType.added, ~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:120:11

TS2322 [ERROR]: Type 'T' is not assignable to type 'never'. value: B[b], ~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:121:11

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.123.0/testing/_diff.ts").DiffType' is not assignable to type 'never'. Type 'import("https://deno.land/std@0.123.0/testing/_diff.ts").DiffType' is not assignable to type 'never'. type: swapped ? DiffType.added : DiffType.removed, ~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:126:11

TS2322 [ERROR]: Type 'T' is not assignable to type 'never'. value: A[a], ~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:127:11

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.123.0/testing/_diff.ts").DiffType' is not assignable to type 'never'. result.unshift({ type: DiffType.common, value: A[a] }); ~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:131:26

TS2322 [ERROR]: Type 'T' is not assignable to type 'never'. result.unshift({ type: DiffType.common, value: A[a] }); ~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:131:49

TS2322 [ERROR]: Type 'string' is not assignable to type 'never'. tokens[tokens.length - 1] += lines[i]; ~~~~~~~~~~~~~~~~~~~~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:287:11

TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'never'. tokens.push(lines[i]); ~~~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:289:23

TS2345 [ERROR]: Argument of type 'DiffResult' is not assignable to parameter of type 'never'. added.push(result); ~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:324:18

TS2345 [ERROR]: Argument of type 'DiffResult' is not assignable to parameter of type 'never'. removed.push(result); ~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:327:20

TS2339 [ERROR]: Property 'value' does not exist on type 'never'. tokenize(a.value, { wordDiff: true }), ~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:341:20

TS2339 [ERROR]: Property 'value' does not exist on type 'never'. tokenize(b?.value ?? "", { wordDiff: true }), ~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:342:21

TS2339 [ERROR]: Property 'details' does not exist on type 'never'. a.details = createDetails(a, tokens); ~~~~~~~ at https://deno.land/std@0.123.0/testing/_diff.ts:353:7
```

These errors show up when `noImplicitAny` is set to false in `compilerOptions`.

**Comment by bartlomieju** [comment]
@kitsonk should we actually guard against this setting?

**Comment by kitsonk** [comment]
Why? It maybe intentional for someone who then is using `--no-check=remote`.

This isn't a bug with `std` either. There maybe a "bug" with TypeScript, but I am not sure the are going to fix it. What is going on is that when `noImplicitAny` is turned on, it enables a lot of CFA features that contextually type things so they don't require type annotations. When you turn it off, you are left with ambigious code that requires more type annotations.

**Comment by bartlomieju** [comment]
> Why? It maybe intentional for someone who then is using `--no-check=remote`.
> 
> This isn't a bug with `std` either. There maybe a "bug" with TypeScript, but I am not sure the are going to fix it. What is going on is that when `noImplicitAny` is turned on, it enables a lot of CFA features that contextually type things so they don't require type annotations. When you turn it off, you are left with ambigious code that requires more type annotations.

Thanks @kitsonk, I wasn't sure either if this is desirable, so that's why I pinged you. `--no-check=remote` was indeed the solution to the problem the user on Discord faced, though it was a bit surprising for me that this problem happened at all. I was under the impression that we use the strictest possible TS settings for `deno_std`.

Closing then.

**Comment by kitsonk** [comment]
> I was under the impression that we use the strictest possible TS settings for `deno_std`.

We do. But with `noImplicitAny` on, TypeScript tightens the control flow analysis (CFA) which allows it to assume more about the code (because it can't be implicitly any) which then allows types to be inferred (strictly) without type annotations.  When you turn that off, lots of types become ambiguous.

Most notably, before advancements in CFA, you would always have to have a type annotation on something like this:

```ts
const a = [];
a.push("b");
```

But with CFA and no implicit any, TypeScript infers that `a` is `string[]`.  With no implicit any off, TypeScript goes for the safe option and infers `never[]`, forcing you to be explicit, effectively regressing TypeScript to old behaviours where we always had to type annotate arrays.

**Comment by bartlomieju** [comment]
Thanks for in-depth explanation @kitsonk, it totally makes sense now.
