### ISSUE TITLE
Potential bug in `signal` function: "module evaluation is still pending"

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno_std#1941]
**Describe the bug**

Code using `signal` is throwing the following error:

```
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.
```

This occurs in a [code example](https://deno.land/manual@v1.19.0/examples/os_signals#async-iterator-example) from the Deno manual

**Steps to Reproduce**

1. Open VS Code in WSL: Ubuntu 20.04
2. Create a `.ts` file with the following code:
```ts
import { signal } from "https://deno.land/std@0.126.0/signal/mod.ts";

const sig = signal("SIGUSR1", "SIGINT");

// Add a timeout to prevent process exiting immediately.
setTimeout(() => {}, 5000);

for await (const _ of sig) {
  console.log("interrupt or usr1 signal received");
}

sig.dispose();
```
3. run the code with `deno run file.ts`
4. after the 5000 ms timeout, the error shows in the terminal

`deno --version`:
```
deno 1.19.0 (release, x86_64-unknown-linux-gnu)
v8 9.9.115.7
typescript 4.5.2
```

**Expected behavior**

The program exits without issues.

The code seems to work fine otherwise, sending a CRTL+C signal during the timeout shows the expected message logged to the terminal, but the error still appears later on

**Environment**

- OS: Ubuntu 20.04, WSL 2
- deno version: 1.19.0
- std version: 0.126.0

**Comment by kt3k** [comment]
There are 2 types async `op`s in Deno: `ref` and `unref`. `ref` op blocks the program existing, and `unref` doesn't.

The above error happens when there's no remaining `ref` ops, but some `unref` op existing and those `unref` ops are blocking some promise resolutions.

Signal polling ops are `unref` type of ops and that causes the above error.

I'm not sure this is a bug or not.

@bartlomieju What do you think?

**Comment by bartlomieju** [comment]
So I think this might be the correct behavior. 

Once timeout is fired off the module evaluation is still pending (because there's a top-level await in this code), but there are no more pending `ref` ops (only `unref` ops coming from signal listener) - so up to this point everything is corret. 

The module evaluation is still pending, because we are "stuck" on the `for await` loop - since we're still waiting for the signals. As a result `sig.dispose()` is never called and so not all module code runs, and then the error is raised because there's no codepath that would allow to execute module in full.

**Comment by GJZwiers** [comment]
Thanks for looking into this! Sounds like it's not a bug then, closing the issue.

**Comment by justinmchase** [comment]
So how are you supposed to handle it then? What is the correct code that would allow you to iterate signal events but not encounter this error?

It sure seems like waiting for a signal forever is a legit case and should hold the process open forever without an error.

**Comment by kt3k** [comment]
> It sure seems like waiting for a signal forever is a legit case and should hold the process open forever without an error.

I think we need to add option to [`addSignalListener`](https://deno.land/api?s=Deno.addSignalListener) to make signal ops block the program from exiting if we want to support that scenario. (That should be suggested in Deno runtime itself instead of the standard library)
