### ISSUE TITLE
log: The file handler only creates a file but doesn't write to it in some cases

### ISSUE THREAD

**Issue by timonson** [denoland/deno_std#2193]
The logger causes strange behavior. The file handler only creates a file but doesn't write to it in some cases. I also tested it with another server, so `Oak` is obviously not the issue here.

In the following example the logger creates the file but doesn't write to `./log.txt`:

```ts
import { Application } from "https://deno.land/x/oak/mod.ts";
import * as log from "https://deno.land/std@0.138.0/log/mod.ts";

export async function debug() {
  await log.setup({
    handlers: {
      console: new log.handlers.ConsoleHandler("DEBUG"),

      file: new log.handlers.FileHandler("WARNING", {
        filename: "./log.txt",
        formatter: "{levelName} {msg}",
      }),
    },

    loggers: {
      default: {
        level: "DEBUG",
        handlers: ["console", "file"],
      },
    },
  });

  const logger = log.getLogger();
  logger.warning(41256);
}

await debug();
const app = new Application();
app.use((ctx) => {
ctx.response.body = "Hello World!";
});
await app.listen({ port: 8000 });

declare global {
  interface ReadableStream<R> {
    getIterator(): any;
  }
}
```

On the other hand, when I remove the server code it works like expected and the message is written to the file:

```ts
import * as log from "https://deno.land/std@0.138.0/log/mod.ts";

export async function debug() {
  await log.setup({
    handlers: {
      console: new log.handlers.ConsoleHandler("DEBUG"),

      file: new log.handlers.FileHandler("WARNING", {
        filename: "./log.txt",
        formatter: "{levelName} {msg}",
      }),
    },

    loggers: {
      default: {
        level: "DEBUG",
        handlers: ["console", "file"],
      },
    },
  });

  const logger = log.getLogger();
  logger.warning(41256); // logs to both `console` and `file` handlers.
}

await debug();
```

- OS: Arch
- deno version:
  - deno 1.21.1 (release, x86_64-unknown-linux-gnu)
  - v8 10.0.139.17
  - typescript 4.6.2
- std version: 0.138.0

**Comment by turuslan** [comment]
Hi.

This is **not** a bug.

### Example
If you change this line in server example ([why 4096?](https://github.com/denoland/deno_std/blob/0.142.0/io/buffer.ts#L250)), you will see file write.
```diff
- logger.warning(41256);
+ logger.warning("x".repeat(4096));
```

### Explanation
`FileHandler` uses [`BufWriterSync`](https://github.com/denoland/deno_std/blob/0.142.0/log/handlers.ts#L126) to [buffer file writes](https://stackoverflow.com/a/33691533).  
So `logger.warning(41256)` doesn't write to file, because 14 bytes string is not enough to fill 4096 buffer.  
Write to file will occur when either there will be more messages to fill buffer (usually apps write a lot of logs), or you manually call `FileHandler.flush`.

Example without server works, because `FileHandler` flushes when Deno process exits (`unload` event, [1](https://github.com/denoland/deno_std/blob/0.142.0/log/handlers.ts#L128), [2](https://github.com/denoland/deno_std/blob/0.142.0/log/handlers.ts#L105-L107), [3](https://github.com/denoland/deno_std/blob/0.142.0/log/handlers.ts#L153-L159)).

[`log` readme](https://github.com/denoland/deno_std/blob/0.142.0/log/README.md#filehandler) also mentions buffer and flush.

### Solution
You may call `file.flush()` (not `logger.flush()`) after each message you want to be written **immediately**, or use timer (e.g. `setInterval`) to write file periodically.

**Comment by timonson** [comment]
Thank you @turuslan for this comprehensive explanation! I know a `log` module has always side effects but this is too much for me :)
