### ISSUE TITLE
it.each in bdd testing style

### ISSUE THREAD

**Issue by ehsan2003** [denoland/deno_std#2213]
**Is your feature request related to a problem? Please describe.**

It is sometimes necessary to run a single test against multiple inputs
but it seems strange to see for loops surrounding test cases.
for example in jest we have some thing like : 
```ts
test.each([
  [1, 1, 2],
  [1, 2, 3],
  [2, 1, 3],
])('.add(%i, %i)', async (a, b, expected) => {
  expect(a + b).toBe(expected);
});
```

**Describe the solution you'd like**

having this feature in deno std so we can easily write tests of this kind

**Describe alternatives you've considered**

some how standardizing the way that we must write for loops for tests
for example mentioning this in the documentation

**Comment by KyleJune** [comment]
I'm against this change because there is an easy alternative to this that is much more flexible. With template strings you can make the title include the variables and with the forEach you can structure your test matrix however you want. Same can be done with describe blocks.

```ts
import { it } from "https://deno.land/std@0.139.0/testing/bdd.ts";
import { assertEquals } from "https://deno.land/std@0.139.0/testing/asserts.ts";

[
  [1, 1, 2],
  [1, 2, 3],
  [2, 1, 3],
].forEach(([a, b, expected]) => {
  it(`add(${a}, ${b})`, () => {
    assertEquals(a + b, expected);
  });
});
```

Output from `deno test example_test.ts`:
```
running 3 tests from ./example_test.ts
add(1, 1) ... ok (6ms)
add(1, 2) ... ok (4ms)
add(2, 1) ... ok (2ms)

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (31ms)
```

This easy alternative that makes use of template strings instead of printf like formatting is part of the reason why I left out implementing functions like jest's `describe.each` and `it.each`.

I think it would be a good idea to add an example of a test matrix to the README.md file though so that it's more clear that you can do this if you want to generate test cases or test groups from an array of values.

**Comment by cmorten** [comment]
Agree with nested arrays, forEach provides equivalence.

Personal main preference with `it.each` like syntax is the tagged template literal support which find far more elegant and expressive that an array of arrays. Don’t know if worth considering?

```js

test.each`
  a    | b    | expected
  ${1} | ${1} | ${2}
  ${1} | ${2} | ${3}
  ${2} | ${1} | ${3}
`('returns $expected when $a is added $b', ({a, b, expected}) => {
  expect(a + b).toBe(expected);
});
```

**Comment by kt3k** [comment]
I agree with @KyleJune 

> ```ts
> import { it } from "https://deno.land/std@0.139.0/testing/bdd.ts";
> import { assertEquals } from "https://deno.land/std@0.139.0/testing/asserts.ts";
> 
> [
>   [1, 1, 2],
>   [1, 2, 3],
>   [2, 1, 3],
> ].forEach(([a, b, expected]) => {
>   it(`add(${a}, ${b})`, () => {
>     assertEquals(a + b, expected);
>   });
> });
> ```

This structure seems covering the case in an enough reasonable way without introducing anything new.

The suggested `each` function introduces the special syntax for it. That feels just confusing, and making test cases a bit harder to understand unnecessarily.
