### ISSUE TITLE
Include an `accept-language` parser

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#2426]
I think it would be useful to include an `accept-language` parser in std. It is very useful when building internationalized websites. Maybe something along the lines of:

```ts
function parse(header: string): Intl.Locale[];
```

**Comment by kitsonk** [comment]
@lucacasonato we have https://github.com/denoland/deno_std/blob/main/http/negotiation.ts#L74 now, which meets this requirement. I don't believe just parsing the header is as useful a content negotiation all together.

**Comment by iuioiua** [comment]
I mostly agree, @kitsonk. My question was does `Intl.Locale` provide some added functionality or benefit to negotiation that I’m not aware of?

**Comment by kitsonk** [comment]
If there is, we should adjust the acceptsLanguage to take `Intl.Locale | string` arguments and return `Intl.Locale` values.

**Comment by iuioiua** [comment]
I like the idea of modifying the current `acceptsLanguages` parser, but I can't see any reason to have `Intl.Locale` as an argument. Are you able to explain?

**Comment by kitsonk** [comment]
Because `acceptsLanguage` takes an [optional set of languages](https://deno.land/std@0.152.0/http/mod.ts?s=acceptsLanguages#overload_1) that are supported by a server.  These should be expressible by either `string` (as supported now) or an instance of `Intl.Locale`.  It would then be able to match on `.language` and `.baseName` without its current string parsing.  It is actually arguable the the implementation should convert strings passed in to `Intl.Locale` instances.

**Comment by iuioiua** [comment]
Yeah, I think this new function might not be needed on second thought. If the user wants to use `Intl.Locale`, they can easily implement it themselves. I've never dealt with internationalisation but still can't see a good reason to use `Intl.Locale` in this instance.

**Comment by lino-levan** [comment]
I agree with iuioiua and kitsonk on this one. I don't think this is really necessary for the reasons that they described.

**Comment by kt3k** [comment]
Ok. Let's close.

@lucacasonato Please reopen if you have any further suggestion/opinion
