### ISSUE TITLE
(node/README.md)Suggestions on detailed introduction of ```Supported modules```

### ISSUE THREAD

**Issue by jerry4718** [denoland/deno_std#2485]
**Is your feature request related to a problem? Please describe.**

Whether to provide a clearer progress table for the ```Supported modules``` in the ```README.md``` introduction of ```--compat``` mode, which is more conducive to the implementation of partners in the community

**Describe the solution you'd like**

|  module   | api  | status  |
|  ----  | ----  | ----  |
| path  | join | √ |
| path  | resolve | × |

or

> path
>> join √
>> resolve ×

**Describe alternatives you've considered**

**Comment by lino-levan** [comment]
This issue is a bit different nowadays but basically boils down to: How can we more clearly explain what node modules are polyfilled, what is missing, what is being worked on, and what is a wontfix. I think there's a little bit of this on https://deno.land/manual@v1.27.1/node/std_node, but the node-compat part of the deno documentation is comedically out of date (and afaik, core team has said they are completely rewriting the manual, so I don't personally want to touch it if it is being reworked).

**Comment by kt3k** [comment]
@lino-levan FYI the manual rewrite was landed at https://github.com/denoland/manual/pull/425, and now you can see the new manual at https://deno.land/manual@main/introduction

> This issue is a bit different nowadays but basically boils down to: How can we more clearly explain what node modules are polyfilled, what is missing, what is being worked on, and what is a wontfix.

I agree that we should be more clear about support status of modules, and have docs for it.

**Comment by kt3k** [comment]
Closing as we migrated `std/node` to `ext/node` and `node/README.md` doesn't exist now.
