### ISSUE TITLE
Print logs from 3rd party library

### ISSUE THREAD

**Issue by darrachequesne** [denoland/deno_std#2506]
**Describe the bug**

It seems calling `log.setup()` interferes with loggers already created with the `getLogger()` method.

I used the documentation [here](https://deno.land/std@0.151.0/log/README.md) as reference.

**Steps to Reproduce**

`index.ts`

```ts
import * as log from "https://deno.land/std@0.150.0/log/mod.ts";
import { foo } from "./3rd-party-lib.ts";

await log.setup({
    handlers: {
        console: new log.handlers.ConsoleHandler("DEBUG"),
    },

    loggers: {
        "my-lib": {
            level: "INFO",
            handlers: ["console"],
        },
    },
});

foo();
```

`3rd-party-lib.ts`

```ts
import { getLogger } from "https://deno.land/std@0.150.0/log/mod.ts";

const logger = getLogger("my-lib");

export function foo() {
    logger.info("foo"); // not printed
    getLogger("my-lib").info("bar"); // printed
}
```

Output:

```
INFO bar
```

**Expected behavior**

I expected `INFO foo` to be printed in the console too.

**Environment**

- OS: Ubuntu 20.04
- deno version:  1.24.1 (release, x86_64-unknown-linux-gnu)
- std version: 0.150.0

Might it be related to https://github.com/denoland/deno_std/pull/1404?

**Comment by lino-levan** [comment]
I'm confused on how this is a bug with std? Unless I'm misunderstanding something, the execution order is as follows:
1. `import * as log from "https://deno.land/std@0.150.0/log/mod.ts";`
2. `import { foo } from "./3rd-party-lib.ts";`
3. `import { getLogger } from "https://deno.land/std@0.150.0/log/mod.ts";`
4. `const logger = getLogger("my-lib"); // fails (silently) because the logger my-lib is not yet initialized`
5.  `export function foo() {`
6. `await log.setup({`
7. `foo();`
8. `logger.info("foo"); // the variable logger never got set up properly because my-lib was not initialized`
9. `getLogger("my-lib").info("bar"); // printed, because obviously it should`

For further justification, we can see that this is the case by modifying `foo` like this:
```typescript
export function foo() {
  console.log(logger.handlers, getLogger("my-lib").handlers) // [] [ ConsoleHandler { level: 10, levelName: "DEBUG", formatter: "{levelName} {msg}" }]
  logger.info("foo"); // nothing
  getLogger("my-lib").info("bar"); // INFO bar
}
```

Unless I'm wrong, this seems like an issue with the program, and not a bug. On the other hand, this behavior is really weird, and maybe we should throw an error or something to let the user know that `getLogger ` failed. What are your thoughts @darrachequesne?

**Comment by darrachequesne** [comment]
@lino-levan you are right, this is not really a bug, but rather a question: how can I, as a library author, provide a way for my users to display the internal logs of the library? (something like https://github.com/visionmedia/debug in the Node.js world)

Calling `getLogger()` every time works fine, but seems a bit counter-intuitive to me (or is it just me?).

**Comment by lino-levan** [comment]
I would imagine that the library author would provide a method for showing internal logs. Something like this:

```typescript
// third_party.ts
import { getLogger } from "https://deno.land/std@0.161.0/log/mod.ts";

let logger = getLogger('third_party')

export function logInternals() { // awful name, but you get it
    logger = getLogger('third_party')
}

export function add(a: number, b: number) { // just some example functionality
    logger.info("Added", a, "+", b)
    return a + b
}
```
```typescript
// mod.ts
import { getLogger } from "https://deno.land/std@0.161.0/log/mod.ts";
import { add, logInternals } from "third_party.ts";

await log.setup({
    handlers: {
        console: new log.handlers.ConsoleHandler("DEBUG"),
    },

    loggers: {
        "third_party": {
            level: "INFO",
            handlers: ["console"],
        },
    },
});

add(4, 1) // no logs
logInternals()
add(1, 4) // logs
```
Besides the fact that this code is kind of gross, I don't see what std can really do to solve this problem. The PR you linked (#1404) kind of addresses this, but it's a pretty huge breaking change (that changes a lot of things in log for this specific problem that in my mind is pretty minor).

Are you asking for anything specific?

**Comment by lino-levan** [comment]
@darrachequesne Sorry to ping again, but ^

**Comment by darrachequesne** [comment]
@lino-levan thanks for your response 👍
