### ISSUE TITLE
Suggest: `Deno.env.get("NODE_DEBUG")` should not permission prompt

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#2507]
I think probably `Deno.env.get("NODE_DEBUG")` should not permission prompt and do a permission check for the env var before requesting it (using `Deno.permissions.query`).

https://github.com/denoland/deno_std/blob/cac7764e3878ac8c2a3c26a1201f3dfcc15e6910/node/internal/util/debuglog.ts#L108

**Comment by devadeka** [comment]
@dsherret I'd like to try my hand at this one if that's alright...

**Comment by devadeka** [comment]
So had a go at it...
I found out how to check whether the permissions for the `NODE_DEBUG` environment variables have been granted used  `Deno.permissions.query`.

Could I please get more clarification on expected behaviour? I am assuming line 108 is only run when permissions are granted. What happens for the other permission states? Should it permission prompt? If so could you point me to docs on how to trigger permission prompts.

Thanks

**Comment by kt3k** [comment]
Introducing TLA in `std/node` has undesired effects on some `esm.sh` modules. See https://github.com/denoland/deno/issues/14243 and https://github.com/denoland/deno_std/issues/2097 for the past discussions.

Because `Deno.permissions.query` is async, querying env permission before getting it doesn't work in this case. (And actually we removed `Deno.permissions.query` call before to avoid the above issues. See https://github.com/denoland/deno_std/pull/2098 )

**Comment by dsherret** [comment]
Oh yeah, I forgot about that. I’m going to close this one, but we should come up with a way to remove this env var check eventually.

**Comment by kt3k** [comment]
> but we should come up with a way to remove this env var check eventually.

I agree. Maybe we can enhance/change CLI somehow to achieve this

**Comment by iuioiua** [comment]
> Introducing TLA in `std/node` has undesired effects on some `esm.sh` modules. See [denoland/deno#14243](https://github.com/denoland/deno/issues/14243) and #2097 for the past discussions.
> 
> Because `Deno.permissions.query` is async, querying env permission before getting it doesn't work in this case. (And actually we removed `Deno.permissions.query` call before to avoid the above issues. See #2098 )

I see. I’ll keep that in mind. Thanks!

**Comment by nayeemrmn** [comment]
> Maybe we can enhance/change CLI somehow to achieve this

@kt3k What do you think about just not checking permissions for `NODE_DEBUG` in cli? Excluding any number of select environment variables from the permission system, as long as they are select, shouldn't be a problem since the alternative is just creating a separate permissionless binding for it which is the same thing.

**Comment by rivy** [comment]
@dsherret , @kt3k , I believe this could now be solved with gating, using the [newly merged synchronous permission functions](https://github.com/denoland/deno/pull/17019).
