### ISSUE TITLE
[perf] deno source code should explicit return type

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#2777]
https://typescript-eslint.io/rules/explicit-function-return-type/

> Functions in TypeScript often don't need to be given an explicit return type annotation. Leaving off the return type is less > code to read or write and allows the compiler to infer it from the contents of the function.
>
> However, explicit return types do make it visually more clear what type is returned by a function. They can also speed up > TypeScript type checking performance in large codebases with many large functions.
>
> This rule enforces that functions do have an explicit return type annotation.

`1 + 1 === 2` at worst case deno test takes 30 seconds, due to type checking is included by default.

https://github.com/denoland/deno/issues/16116

https://deno.land/std@0.158.0/node/assert.ts?source#L240

**Comment by kt3k** [comment]
We intentionally don't write return types if they are `void` or `Promise<void>`. We consider those are unnecessary boilerplate

ref: https://github.com/denoland/deno/issues/8832

Also the performance issue reported in https://github.com/denoland/deno/issues/16116 looks like caused by the network download, not by typing issue. `deno test` now doesn't type check the remote modules by default. ref: https://deno.com/blog/v1.23#no-type-checking-by-default
