### ISSUE TITLE
Streaming stdin using `process.stdin` does not work

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#2974]
```ts
import { process } from "https://deno.land/std@0.167.0/node/process.ts";

function readStdin(): Promise<string> {
  return new Promise((resolve, reject): void => {
    let code = "";

    process.stdin.setEncoding("utf8");

    process.stdin.on("readable", function () {
      const chunk = process.stdin.read();
      if (chunk !== null) code += chunk;
    });

    process.stdin.on("end", function () {
      resolve(code);
    });
    process.stdin.on("error", reject);
  });
}

console.log(await readStdin());
```

This blocks parts of `@babel/cli` from running in NPM compat.

**Comment by lucacasonato** [comment]
It looks to be the `process.stdin.on("readable", ...)` call.

**Comment by kt3k** [comment]
@PolarETech 

> highWaterMark: Deno.isatty?.(Deno.stdin.rid) ? 0 : undefined

Does Node.js set the same value to `highWaterMark` of stdin?

**Comment by PolarETech** [comment]
@kt3k

I checked the actual value in Node.js with the following sample code.

```mjs
// test.mjs
import process from "node:process";

(() => {
  new Promise((resolve, reject) => {
    console.log("highWaterMark:", process.stdin.readableHighWaterMark);

    process.stdin.setEncoding("utf8");
    process.stdin.on("readable", () => {
      console.log("chunk:", process.stdin.read());
    });
    process.stdin.on("end", () => {
      console.log("end");
      resolve;
    });
    process.stdin.on("error", reject);
  });
})();

// dummy.txt
foo
```

The execution results are as follows.

```bash
% node test.mjs
highWaterMark: 0
foo # User Input
chunk: foo

% node test.mjs < dummy.txt
highWaterMark: 65536
chunk: foo
chunk: null
end
```

From the results, I suppose the `highWaterMark` is:

- for tty: `0`, the same as `tty.ReadStream`
  https://github.com/nodejs/node/blob/9ca57fae11836af6cc8044efea89ec392356ccbb/lib/tty.js#L60
- for file: `65536`, the same as `fs.ReadStream`
  https://github.com/nodejs/node/blob/9ca57fae11836af6cc8044efea89ec392356ccbb/lib/internal/fs/streams.js#L155

---

Sorry, I have just noticed that the default value of `highWaterMark` in `Readable` is `16384`, not `65536`. I should have passed `64 * 1024` instead of `undefined`.
https://github.com/nodejs/readable-stream/blob/7fdb3b4ec5135e586d5c6695f7e08d04f268b1cb/lib/internal/streams/state.js#L11-L13

```diff
/** https://nodejs.org/api/process.html#process_process_stdin */
export const stdin = stdio.stdin = new Readable({
-  highWaterMark: 0,
+  highWaterMark: Deno.isatty?.(Deno.stdin.rid) ? 0 : 64 * 1024,
  emitClose: false,
  read(size) {
```

I would appreciate it if you could point out any errors in my understanding.

**Comment by kt3k** [comment]
@PolarETech Thanks for looking into it further. The suggested solution looks good to me
