### ISSUE TITLE
Add getRoot and removeTreeNode methods to RedBlackTree and BinarySearchTree.

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#3055]
**Is your feature request related to a problem? Please describe.**

A node can be removed from a binary tree with O(1) time complexity using the removeTreeNode method.

Add getRoot and removeTreeNode methods to RedBlackTree and BinarySearchTree.

https://deno.land/std@0.170.0/collections/binary_search_tree.ts?source

https://deno.land/std@0.170.0/collections/red_black_tree.ts?source

**Describe the solution you'd like**

```ts
  getRoot() {
        return this.root;
    }
```

https://github.com/masx200/leetcode-test/blob/b52ad069dbeb43f8f155ccbc3687c87a631bfdbe/dinner-plate-stacks/RedBlackTree.ts#L8

**Describe alternatives you've considered**

https://www.npmjs.com/package/@datastructures-js/binary-search-tree#root

**Comment by masx200** [comment]
We can also add the method reverseInOrderIterator for BinarySearchTree.

```ts
export function* reverseInOrderIterator<
    T extends { left: T | null; right: T | null },
>(root: T | null): Generator<T> {
    if (!root) {
        return;
    }
    yield* reverseInOrderIterator(root.right);
    yield root;
    yield* reverseInOrderIterator(root.left);
}
```

**Comment by lino-levan** [comment]
Both the `BinarySearchTree` and `RedBlackTree` have O(1) node removal and reverse-in-order tree traversal already.

I'm not sure what the use case of getting the root is, but I will open a PR for this functionality.

**Comment by masx200** [comment]
```ts
removeTreeNode(removeNode: RedBlackNode<T>) {
        const successorNode: RedBlackNode<T> | null = (
            !removeNode.left || !removeNode.right
                ? removeNode
                : removeNode.findSuccessorNode()!
        ) as RedBlackNode<T>;
        const replacementNode: RedBlackNode<T> | null = successorNode.left ??
            successorNode.right;
        if (replacementNode) replacementNode.parent = successorNode.parent;

        if (!successorNode.parent) {
            this.root = replacementNode;
        } else {
            successorNode.parent[successorNode.directionFromParent()!] =
                replacementNode;
        }

        if (successorNode !== removeNode) {
            removeNode.value = successorNode.value;
            removeNode = successorNode;
        }
        this._size--;
        const node = removeNode;
        if (node && !node.red) {
            this.removeFixup(node.parent, node.left ?? node.right);
        }
        return;
    }
```

**Comment by pting-me** [comment]
I believe the ask here is to be able to remove by node rather than by value. Current [`remove` says complexity is `O(log n)`](https://github.com/denoland/deno_std/blob/main/collections/binary_search_tree.ts#L21) rather than `O(1)` complexity.

Not sure what exactly the use case is, but you'll see this sort of thing in [C++ stl](https://cplusplus.com/reference/set/set/erase/).

**Comment by lino-levan** [comment]
@pting-me thanks for the clarification, this makes a lot more sense in my head now.

>  believe the ask here is to be able to remove by node rather than by value.

Currently it looks like the std does not expose the nodes directly to methods. This seems to be an explicit design decision, but honestly not too sure what the reasoning is there.

> Current [remove says complexity is O(log n)](https://github.com/denoland/deno_std/blob/main/collections/binary_search_tree.ts#L21) rather than O(1) complexity.

This is just a result of it being by value instead of by node. By definition, removing by value involves first *finding* the node (in O(log n) time complexity), and then doing the removal method (in O(1) time complexity). In the least helpful way possible, "removing a node" does technically take O(1) time complexity even if the current api only allows us to do this after a O(log n) search.

Essentially this issue is proposing opening up the TreeNode methods on the tree classes to the public api. I'm not sure how to feel about this one. Would appreciate some community feedback.

**Comment by pting-me** [comment]
@lino-levan That was my take on it too.

Also wanted to mention, unlike the `RedBlackTree`, `BinarySearchTree` is unbalanced. I believe removing by node for the BST would also have to be `O(log n)` because it relies on `findSuccessorNode`.

I think it would be more helpful to get context on the use cases. Not really sure, but my take is that this is basically an alternate implementation of [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), since V8 uses a hashmap.

@KyleJune Do you have any thoughts? I noticed you are the original author.

**Comment by lino-levan** [comment]
I haven't looked hard enough at the implementation but regardless of the balancing of the tree, the operation should take O(1) time. I'm skeptical that the current BinarySearchTree implementation is O(log n) but I will check when I have a moment.

**Comment by KyleJune** [comment]
> @KyleJune Do you have any thoughts? I noticed you are the original author.

Thanks for tagging me on this issue.

> Currently it looks like the std does not expose the nodes directly to methods. This seems to be an explicit design decision, but honestly not too sure what the reasoning is there.

Yes, this was intentional to prevent users from unintentionally breaking the tree. It also makes it more clear how the tree should be used. Instead of having to decide if I should use findNode or find, find is my only option.

I made the internal functions used by the tree protected so that the datastructures could be extended to create new data structures. For example, RedBlackTree extends BinarySearchTree to add self balancing.

I still believe that we should not expose these functions but I wouldn't be opposed to refactoring to make it so that you can remove by node.

I believe changing [removeNode on the BinarySearchTree](https://deno.land/std@0.170.0/collections/binary_search_tree.ts?source#L238) to take a node instead of a value would make sense. I'd suggest the following call signature.

```ts
protected removeNode(node: BinarySearchNode<T>): BinarySearchNode<T>;
```

Then all the places that use it would need to be updated to find before calling removeNode. For example, this is what I would change the `remove` function on the `BinarySearchTree` to do.

```ts
protected removeNode(value: T): BinarySearchNode<T> | null {
  const node: BinarySearchNode<T> | null = this.findNode(value);
  return !!(node && this.removeNode(node));
}
```

This would then make it possible to extend RedBlackTree to create other data structures like an OrderedMap. An ordered map would have an o(1) worst case for find and remove operations. It could do that by keeping an internal map of values to RedBlackNodes. Nodes would be added to the map on insertion and removed when the node is removed from the tree.
