### ISSUE TITLE
colors/mod.ts: brightBlue looks more like magenta

### ISSUE THREAD

**Issue by sspilleman** [denoland/deno_std#3064]
**Describe the bug**

Using the color std module. If you want to output brightBlue the output txt looks (almost) like magenta. 
bgBlue, bgBrightBlue, blue work ok

**Steps to Reproduce**

```javascript
console.log("brightBlue", brightBlue("brightBlue"));
```

**Expected behavior**

The output should look like (bright) blue

**Environment**

- OS: macOS Ventura 13.1
- deno version: 1.29.1 (release, aarch64-apple-darwin)
- std version: 0.164.0

<img width="582" alt="image" src="https://user-images.githubusercontent.com/592486/209775282-1a3d6cae-d121-403d-8a90-2405533fe469.png">

**Comment by kamilogorek** [comment]
Can you report your `echo $TERM`?

It looks fine for me (using `screen-256color`):
<img width="198" alt="image" src="https://user-images.githubusercontent.com/1523305/209809280-fda0fb3f-d439-4f04-aab0-c89baf7eddfe.png">

You can also use `msgcat --color=test` to display renderings all available colors in your terminal.

**Comment by sspilleman** [comment]
Output of `echo $TERM `:
```
xterm-256color
```
Output of `msgcat --color=test `:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/592486/209832677-77afebea-f4bd-46f4-9bf4-b4d0764988ca.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/592486/209832727-f943bbfd-e334-4a4f-9329-c516c49caaa8.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/592486/209832837-f9474445-b636-4834-ae1f-d24ebbd4cc14.png">

**Comment by kamilogorek** [comment]
This is a valid behavior then. Based on your output, this is exactly how it should look for `xterm`, see: https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit
You can either change your term to `screen-256color` which will give you a different set of colors, or modify settings of your terminal emulator to update color codes for the one you want.
This is a user-specific configuration and escape codes are standardized, so there's nothing we can change here tbh.

**Comment by sspilleman** [comment]
Thanks! ...appreciate your answer!

Still thinking about this though. xterm-256color is the default on macOS right? Shouldn't it look "good" with the default settings on a platform that is so widely used as a dev platform?
If people start changing the defaults they run into the risk of messing things up which should be okay-ish I guess.

What are your thoughts on this?

**Comment by kamilogorek** [comment]
> Still thinking about this though. xterm-256color is the default on macOS right?

That is correct for `terminal.app`, other emulators may override it. But that's not an issue anyway, as the problem here is that afair, `xterm` do not encode color values. This means that it will differ entirely based on the app itself (iterm2 being a very popular alternative for example).

Here's a comparison of iterm (left) vs terminal.app (right), with the same, `xterm-256color` setting:

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/1523305/209932144-853384bc-d8c8-491e-9c56-a2929865df89.png">

> Shouldn't it look "good" with the default settings on a platform that is so widely used as a dev platform?

It definitely should, however, we have quite tied hands here, as again, this is standardized escape code, and its output can only be modified by the end user. Terminal color palette is what chooses the color itself.
Also, the most common JS library for colors also follows the same standard - https://www.npmjs.com/package/ansi-styles
https://github.com/chalk/ansi-styles/blob/c325165daa029dad038c12118d2bf20aa4cf3a77/index.js#L39

https://www.npmjs.com/package/ansi-styles

> BTW, Are there any negative drawbacks if I would change from xterm-256color to screen-256color?

Not really, they have basically the same support (which is based on https://man7.org/linux/man-pages/man5/terminfo.5.html database, but that's too convoluted for anyone to understand haha). However not all emulators will understand the change, eg. terminal.app will happily ignore your change, but if you use `tmux` within it, it will work just fine (I personally use tmux+screen256, which is tmux's default (well kinda, it uses tmux-256 and screen-256 as fallback)).

**Comment by lino-levan** [comment]
I think @kamilogorek has done a pretty good job explaining why this is pretty much unactionable.

Unless @sspilleman has a proposal for what can be done, I think this issue should be closed as an issue with terminal.app and not with the deno std.

**Comment by sspilleman** [comment]
Indeed! Very good explanation! Thanks for that!
