### ISSUE TITLE
Add method toArray to Heap

### ISSUE THREAD

**Issue by masx200** [denoland/deno_std#3076]
**Is your feature request related to a problem? Please describe.**

Add method toArray to Heap

https://github.com/denoland/deno_std/blob/7afe49284d0b5357eaf0f5668080cd26f13a1d8b/collections/binary_heap.ts#L62

Returns the underlying cloned array in arbitrary order without sorting

**Describe the solution you'd like**

```ts
toArray(){

return Array.from(this.#data)

}
```

**Describe alternatives you've considered**

https://github.com/datastructures-js/heap/issues/31

**Comment by timreichen** [comment]
This is a one liner. Does it really need a method for it?

**Comment by masx200** [comment]
At present, there is a symbol.iterator method, but its time complexity is o (nlogn), while the time complexity of toArray is O (n), so there is no need for sorting.

**Comment by 0f-0b** [comment]
`toArray` would return the elements in arbitrary order similar to Rust's [`BinaryHeap::into_vec`](https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.into_vec), and may be useful when sorting is unneeded. This cannot be implemented efficiently in user code because it directly accesses `#data`.

**Comment by iuioiua** [comment]
Perhaps, just make `.#data` a public property?

**Comment by duncanmak** [comment]
I was using BinaryHeap and didn't expect that simply by converting it into an array for reading would also drain the heap, maybe that should be better documented.
