### ISSUE TITLE
TOML frontmatter extraction should look between +++ instead of ---

### ISSUE THREAD

**Issue by jpcaruana** [denoland/deno_std#3094]
**Describe the bug**

**Steps to Reproduce**

extract TOML frontmatter from a hugo/zola blog post:

```
+++
title = "Title"
+++
Content
```

using https://deno.land/std@0.171.0/encoding/front_matter/toml.ts doen't extract the frontmatter at all as it looks between `---`instead of `+++`

**Expected behavior**

Extract the TOML frontmatter contained within `+++`

**Environment**

- OS: MacOS 12.4
- deno version: 1.29.2 / v8 10.9.194.5 / typescript 4.9.4
- std version:0.170.0

see https://github.com/denoland/deno_std/blob/main/encoding/front_matter/mod.ts#L176 where separator for TOML is `---` instead of `+++` (as described in https://gohugo.io/content-management/front-matter/#front-matter-formats)

**Comment by kt3k** [comment]
Is this convention common across tools? Or specific to Hugo?

**Comment by lino-levan** [comment]
It's definitely not in the spec (ref: https://github.com/toml-lang/toml/issues/511). I think that this is application-specific, but I honestly don't see a lot of tools that use toml front matter in general. I would be okay with changing it just because of Hugo because Hugo is the only tool I know of that even offers it as an option.

Alternatively, maybe this is an option we can provide instead (though that looks to be difficult given there is a lot of regex involved)?

As an aside: for a language that claims to be designed around simplicity, parsing it sure seems to be a nightmare.

**Comment by lino-levan** [comment]
I guess the better question is: are there tools that DON'T user `+++` as the TOML delimiter? If so, then this is a breaking change for (in my opinion), limited gain.

Why don't we parse `---` `---toml` AND `+++` instead of just picking between `---` and `+++`? I feel like that would be the best for everyone in this situation.

**Comment by kt3k** [comment]
I researched a bit about toml front matter support across tools:

### `+++`

- Forestry also uses `+++` https://forestry.io/docs/faqs/glossary/front-matter/#toml

(in addition to zola and hugo)

### `---toml`

- 11ty uses `---toml` (via gray-matter) https://www.11ty.dev/docs/data-frontmatter-customize/
- vuepress uses `--toml` (via gray-matter) https://vuepress.vuejs.org/guide/frontmatter.html#alternative-frontmatter-formats
- gatsby, gridsome also use gray-matter internally. Probably the same rule applies to it.

(further inputs are very welcome)

---

It looks reasonable to add `+++` support to toml front matter, but let's keep `---toml` as it looks also common across tools. I agree with the suggestion by @lino-levan

**Comment by lino-levan** [comment]
Good to know I'm not completely off base 😄. Cool to see a more complete analysis of tools.
