### ISSUE TITLE
`node:child_process`: `exec` commands are not recognized when using `cmd`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno_std#3146]
`exec` does not execute commands in the default shell on Windows.

```js
import { exec } from 'node:child_process';

const { stdout, stderr } = exec('deno --version');
stdout.on("data", (chunk) => {
    console.log("STDOUT: " + chunk);
});
stderr.on("data", (chunk) => {
    console.log("STDERR: " + chunk);
});
```

```
deno run -A exec.mjs
STDERR: '\"deno --version\"' is not recognized as an internal or external command,
operable program or batch file.
```

With `shell: "powershell"` option:

```js
import { exec } from 'node:child_process';

const { stdout, stderr } = exec('deno --version', {
    shell: "powershell",
});
stdout.on("data", (chunk) => {
    console.log("STDOUT: " + chunk);
});
stderr.on("data", (chunk) => {
    console.log("STDERR: " + chunk);
});
```

```
deno run -A exec.mjs
STDOUT: deno 1.30.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

Related to: https://github.com/denoland/deno/issues/17558, https://github.com/denoland/deno/issues/16714

**Comment by tmchein** [comment]
I've been reading into the child_process and I've found no solutions but one that might be temporary for your issue, I used {shell: "powershell"} and deno run -A exec.mjs and it worked using CMD.

![image](https://user-images.githubusercontent.com/30534965/215287584-f2529929-9719-47a2-8fe7-04491791e798.png)

**Comment by GJZwiers** [comment]
@tmchein Thanks for looking into it, but the issue is that there are some npm packages using `exec` that won't work in Deno until this bug is fixed.

**Comment by kt3k** [comment]
@GJZwiers 
> some npm packages using exec

Can you give examples of these modules?

**Comment by kt3k** [comment]
We would prioritize this issue more if it affects popular modules

**Comment by GJZwiers** [comment]
> @GJZwiers
> 
> > some npm packages using exec
> 
> Can you give examples of these modules?

So far it is known to affect `@azure/identity` and the `synth` command from `aws-cdk`

**Comment by PolarETech** [comment]
This is probably a problem caused by not executing `normalizeSpawnArguments()` within `child_process.spawn()`.

The Node.js documentation has the following description of `child_process.spawn` function's `options`. ([Link](https://nodejs.org/dist/latest-v18.x/docs/api/child_process.html#child_processspawncommand-args-options))

> `windowsVerbatimArguments` \<boolean\> No quoting or escaping of arguments is done on Windows. Ignored on Unix. This is set to `true` automatically when `shell` is specified and is CMD. Default: `false`. 

The process of setting `windowsVerbatimArguments` to `true` when the condition is met is in `normalizeSpawnArguments()`.

https://github.com/denoland/deno_std/blob/1cda9238eaa24b26fd34e1d5963906ed1bcdd301/node/internal/child_process.ts#L549-L551

Refs: [Node.js src](https://github.com/nodejs/node/blob/v18.12.1/lib/child_process.js#L617)

This function should be executed within the `spawn()`, but is not currently.

https://github.com/denoland/deno_std/blob/1cda9238eaa24b26fd34e1d5963906ed1bcdd301/node/child_process.ts#L163-L174

Refs: [Node.js src](https://github.com/nodejs/node/blob/v18.12.1/lib/child_process.js#L736)
