### ISSUE TITLE
refactor(semver): make SemVer class immutable

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3164]
SemVer class mutates its properties based on the method calls. Especially the mutation of `this.raw` property is problematic.

We should make this class immutable.

See the comment in https://github.com/denoland/deno_std/pull/3157 for more context

**Comment by justinmchase** [comment]
I would be willing to take a shot at this when / if the time is right, it would be a breaking change that would probably justify a major version increment.

**Comment by bartlomieju** [comment]
> I would be willing to take a shot at this when / if the time is right, it would be a breaking change that would probably justify a major version increment.

@justinmchase since `deno_std` is still `0.x.y` it's considered unstable. A breaking change is fine if this is the preferable API.

**Comment by justinmchase** [comment]
Ok well I'll take a crack at it and we can see how we like it.

**Comment by timreichen** [comment]
I wonder if we even need a semver class or should just remove it. Semver parse, format, compare, increment etc. is pretty much stateless, so functions would work well enough.

**Comment by justinmchase** [comment]
No, I don't think you do. I would just export everything as functions. Turn the `class` into a simple `type` or `interface` have the behavior be in the exported functions rather than as members of a class, always return a _new_ object (or string as appropriate) for those functions.

Some of the functions have an `if (semver instanceof SemVer)` check right now, which is problematic. If two different libraries import slightly different versions of semver and pass instsances too each other then they'll have problems possibly. It would just be a lot better in general to get rid of the class.

**Comment by justinmchase** [comment]
Here's a WIP

https://github.com/denoland/deno_std/pull/3169

**Comment by justinmchase** [comment]
Yeah, precisely. There are a lot of weirdnesses like that. The raw can change based on whether or not you've called certain other functions, not good.

Can you try out #3169 and see if it works more like you'd expect? Try out the API and see if there is anything you'd like to be different? I think some community feedback may help the PR progress.
