### ISSUE TITLE
common utility types

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno_std#3196]
There are many commonly-copy-pastaed utility types (such as `UnionToIntersection`), which haven't made their way into TS as intrinsic. Thoughts on including some obvious ones in a top-level `types` dir?

I did an issue search for "type utilities" and found nothing relevant (hopefully this isn't a duplicate).

**Comment by lino-levan** [comment]
This seems reasonable. Do you have a list in mind? Is there a popular node alternative?

I'd love to get a second opinion from @iuioiua and/or @kt3k on whether this makes sense for `/std` (or whether a third-party module on `/x` would make more sense).

**Comment by iuioiua** [comment]
I think `testing/types.ts` is what you're after. It'd make sense to add any utilities there.

**Comment by harrysolovay** [comment]
> I think `testing/types.ts` is what you're after

It isn't. Those types are for crafting type-level tests (they come directly from dsherret's `conditional-type-checks`). What I'm describing is for more than just testing.

> whether this makes sense for `/std` (or whether a third-party module on `/x` would make more sense).

Depends on the utility types included / how opinionated. A `UnionToIntersection` type is very unopinionated / common. Given that std is the first dependency for which Deno developers reach, I believe it would make sense to include such unopinionated / common types here.

> Do you have a list in mind?

Some initial ones:

**`UnionToIntersection`**

```ts
export type UnionToIntersection<Union> = (Union extends any ? (_: Union) => any : never) extends (
  _: infer Intersection,
) => any
  ? Intersection
  : never
```

**`ValueOf`**

```ts
export type ValueOf<T> = T[keyof T]
```

**`Flatten`**

```ts
export type Flatten<T> = T extends object
  ? {
      [Key in keyof T]: Flatten<T[Key]>
    }
  : T
```

**`OptionalKey`**

```ts
export type OptionalKey<T> = keyof {
  [K in keyof T as (undefined extends T[K] ? K : never)]: T[K]
} 
```

**Comment by iuioiua** [comment]
> It isn't. Those types are for crafting type-level tests (they come directly from dsherret's `conditional-type-checks`). What I'm describing is for more than just testing.

The location and documentation may be misleading. Those type checks may apply to more than just testing scenarios.

> Depends on the utility types included / how opinionated. A `UnionToIntersection` type is very unopinionated / common. Given that std is the first dependency for which Deno developers reach, I believe it would make sense to include such unopinionated / common types here.

I agree.

> Some initial ones:
> 
> **`UnionToIntersection`**
> 
> ```ts
> export type UnionToIntersection<Union> = (Union extends any ? (_: Union) => any : never) extends (
>   _: infer Intersection,
> ) => any
>   ? Intersection
>   : never
> ```
> 
> **`ValueOf`**
> 
> ```ts
> export type ValueOf<T> = T[keyof T]
> ```
> 
> **`Flatten`**
> 
> ```ts
> export type Flatten<T> = T extends object
>   ? {
>       [Key in keyof T]: Flatten<T[Key]>
>     }
>   : T
> ```
> 
> **`OptionalKey`**
> 
> ```ts
> export type OptionalKey<T> = keyof {
>   [K in keyof T as (undefined extends T[K] ? K : never)]: T[K]
> } 
> ```

These sound like a good starting base for a top-level `std/types` module. Perhaps, it'd also be worth moving some of the code from `testing/types.ts` into that same `std/types` module for the same reason mentioned above.

**Comment by lino-levan** [comment]
I'm slightly -1 for a `std/types` top level module. I don't think `testing/types.ts` is the right place for these utilities but I don't really know where else they would go.

**Comment by tjjfvi** [comment]
Being able to reduce the duplication of these types is good, but I think this problem would be better solved by a dedicated type utility library, and not in Deno std.

Delving into some of the type suggestions can show some reasons why. (Not to pick on the suggestions; they're just the ones at hand.)

## UnionToIntersection

> ```ts
> export type UnionToIntersection<Union> = (Union extends any ? (_: Union) => any : never) extends (
>   _: infer Intersection,
> ) => any
>   ? Intersection
>   : never
> ```

Most people expect `U2I<T>` to always be assignable to `T`, but this definition doesn't uphold that. One can fix this by changing it to `? Extract<Intersection, Union>`, but this makes it a less valid U2I, as it makes `U2I<never>` be `never` instead of the proper `unknown`[^1].

[^1]: `U2I<never> = unknown` may seem counterintuitive, but `U2I<A | B>` should always be equal to `U2I<A> & U2I<B>`. If `B = never`, then `A | B = A`, so `U2I<A> = U2I<A | never> = U2I<A> & U2I<never>`. The only way this is satisfied in all cases is `U2I<never> = unknown`.

Most of the time, one doesn't actually want a verbatim U2I type. For example, let's say one wanted to write a type that was `AssignableToAllTupleElements`. In other words, `AssignableToAllTupleElements<[A, B, C]> = A & B & C`.

One might think to write
```ts
type AssignableToAllTupleElements<T extends unknown[]> = U2I<T[number]>
```

But this won't work on, say, `[string | number]` (it'll return `never`).

What one needs to write, if continuing to use a predefined `U2I` type, is:
```ts
type AssignableToAllTupleElements<T extends unknown[]> =
  (U2I<{ [K in keyof T]: { x: T[K] } }[number]> & { x: unknown })["x"]
```

Here, wrapping it in the `{ x: ... }` protects the inner union from being distributed over.

However, it's usually easier to inline `U2I`:
```ts
type Contra<T> = (x: T) => void
type AssignableToAllTupleElements<T extends unknown[]> =
  { [K in keyof T]: Contra<T[K]> }[number] extends Contra<infer U> ? U : never
```

This skips the `{ x: ... }` wrapper entirely by going straight to the contravariant wrapper.

## ValueOf

> ```ts
> export type ValueOf<T> = T[keyof T]
> ```

The core issue with `ValueOf` is:
```ts
type X = ValueOf<[1, 2, 3]>
```

One would likely expect this to be `1 | 2 | 3`; however, it is actually
```ts
type X = 3 | 1 | 2 | (() => IterableIterator<3 | 1 | 2>) | (() => {
    copyWithin: boolean;
    entries: boolean;
    fill: boolean;
    find: boolean;
    findIndex: boolean;
    keys: boolean;
    values: boolean;
}) | ... 28 more ... | ((searchElement: 3 | ... 1 more ... | 2, fromIndex?: number | undefined) => boolean)
```

In most cases, it's best to just write the `[keyof T]` (or `[number]` for tuples).

## Flatten

> ```ts
> export type Flatten<T> = T extends object
>   ? {
>       [Key in keyof T]: Flatten<T[Key]>
>     }
>   : T
> ```

This type is often used as an identity type that simply simplifies the hover, but this recursive form has incorrect results, and the `T extends object` doesn't offer the safety one might expect.

```ts
class Foo { private foo: string = "abc" }
type Bar = string & { __barBrand: undefined }

type X = Flatten<{ a: Foo }> // { a: {} }
type Y = Flatten<{ a: () => void }> // { a: {} }
type Z = Flatten<{ a: Bar }> // { a: { [x: number]: string; toString: {}; charAt: {}; ... __barBrand: undefined; } }
```

A proper form of this type is:
```ts
type Expand<T> = T extends T ? { [K in keyof T]: T[K] } : never
```
This will still mangle types like `Foo` or `Bar`, so it should only ever be called on things that you know are object types.

## OptionalKey

> ```ts
> export type OptionalKey<T> = keyof {
>   [K in keyof T as (undefined extends T[K] ? K : never)]: T[K]
> }
> ```

This type, as written, finds the keys that `undefined` is assignable to, which is different from the keys which are optional. Both of these should be `never`:
```ts
type X = OptionalKey<{ a: string | undefined }> // "a"
type Y = OptionalKey<{ a: unknown }> // "a"
```

The desired type could be written as
```ts
export type OptionalKeys<T> = keyof {
  [K in keyof T as {} extends Pick<T, K> ? K : never]: T[K]
}
```
(This also picks up index signatures, which are arguably optional, especially under `noUncheckedIndexedAccess`, but may be unexpected.)

## IsExact

Finally, let's look at a utility type that's already included in deno std: [`IsExact`](https://deno.land/std@0.177.0/testing/types.ts?source#L85).

This is supposed to check for "exact matching", but it really checks for deep structural cross-assignability modulo `any`. There are many ways that this can return a false-positive:
```ts
class Foo<T> { declare private _: T }

// all of the following should be false
type A = IsExact<() => void, (x?: number) => void> // true
type B = IsExact<Foo<{ x: 1, a?: 1 }>, Foo<{ x: 1, b?: 1 }>> // true
type C = IsExact<() => any, () => number> // true
type D = IsExact<Foo<any>, Foo<number>> // true
type E = IsExact<{ a: 1 }, { readonly a: 1 }> // true
```

The best definition of this type is
```ts
type IsEqual<X, Y> = (<T>() => T extends X ? true : false) extends (<T>() => T extends Y ? true : false) ? true : false
```

This uses TS's native equality comparison, and so it correctly returns false for all the above examples. However, this correct equality may still be stricter than some expect.

## Conclusion

The problem with type utility libraries is that it is nearly impossible to semver TS types. Generic types are so complex that there is no strict subset of behavior that one can define as public API, and so pretty much any change to a type alias is a breaking change.

Because of this, as issues are discovered with types, either a type utility library has to make frequent breaking changes, or else progressively become a graveyard of deprecated types.

Frequent breaking changes are fine for a type utility library that can separately version each type, but they're not good for Deno std, since all std modules share one version.

One of Deno's biggest strengths is that it is easy to pull in tiny libraries with minimal overhead. A `ts-is-equal` package on NPM would be bloated overkill, but `https://deno.land/x/ts-is-equal/mod.ts` is very lightweight.

**Comment by harrysolovay** [comment]
Closing per @tjjfvi's thoughtful arguments against including utility types.
