### ISSUE TITLE
Uncaught TypeError: core.runMicrotasks is not a function

### ISSUE THREAD

**Issue by anonrig** [denoland/deno_std#3201]
Running this code throws error:

```
import { bench, run } from "https://esm.sh/mitata"

const url = 'https://example.com'

bench('new URL', () => new URL(url))

await run()
```

Error:

```
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.153.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.153.0/node/process.ts:312:7
    at innerInvokeEventListeners (internal:ext/web/02_event.js:776:9)
    at invokeEventListeners (internal:ext/web/02_event.js:816:7)
    at dispatch (internal:ext/web/02_event.js:685:11)
    at dispatchEvent (internal:ext/web/02_event.js:1066:14)
    at [internal:cli/worker.rs:90:39]:1:1
```

**Comment by anonrig** [comment]
Specifically with this command: `deno run -A url/deno.js` and on this file: https://github.com/anonrig/node-benchmarks/blob/main/url/deno.js

**Comment by bartlomieju** [comment]
Which Deno version are you using?

**Comment by anonrig** [comment]
```
➜  node-benchmarks git:(main) ✗ deno --version
deno 1.30.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by bartlomieju** [comment]
It seems you have a cached version of `mitata` downloaded - if you run with `--reload` flag the problem should go away. The root cause of the problem: in v1.30 we removed `Deno.core` namespace (which was never meant to be public API) and the old version of std (0.153.0 we see in the stack trace) can't handle that, but the newer version of std can handle that. Let me know if that solves the problem.

**Comment by anonrig** [comment]
It solved the issue. Thanks.
