### ISSUE TITLE
Type signature of `assertArrayIncludes` is misleading when used with strings

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno_std#3372]
**Describe the bug**

`assertArrayIncludes` takes `ArrayLike<T>` as both its first and second parameters. Both `string` and `string[]` satisfy `ArrayLike<string>`, leading to unexpected behavior.

**Steps to Reproduce**

```ts
assertArrayIncludes(['a', 'b'], 'ab') // passes (expected to fail)
assertArrayIncludes(['ab', 'cd'], 'ab') // fails (expected to pass)
```

The fix is to pass the 2nd argument as an array of strings:

```ts
assertArrayIncludes(['a', 'b'], ['ab']) // fails as expected
assertArrayIncludes(['ab', 'cd'], ['ab']) // passes as expected
```

However, this isn't apparent from the type signature and is counter-intuitive based on the assumption that `assertArrayIncludes(a, b)` would work something like `if (!a.includes(b)) throw err`.

**Expected behavior**

Any one of the following:
1. Type checking to fail when passing `(string[], string)`
2. The second argument to be a scalar (breaking change — checking for existence of multiple elements would then need to be done via explicitly iterating)
3. The second argument to be automatically wrapped in an array

**Environment**

- OS: Windows 11
- deno version: 1.33.2
- std version: 0.186.0

**Comment by lino-levan** [comment]
`assertArrayIncludes` isn't super intuitive to me as it currently stands. I think it would be more intuitive if we did option 3, though it does involve some pretty gross type checking on the function side so maybe not. Perhaps failing type checking is the best course of action.

**Comment by timreichen** [comment]
Is it an option fix this by changing the parameter types? `T[]` instead of `ArrayLike<T>` for example?

**Comment by ayame113** [comment]
I'm in favor of changing the parameter type (I think `Exclude<ArrayLike<T>, string>` would be fine too).

**Comment by jsejcksn** [comment]
https://github.com/denoland/deno_std/blob/0.188.0/testing/asserts.ts#L449-L489

```ts
/**
 * Make an assertion that `actual` includes the `expected` values.
 * If not then an error will be thrown.
 *
 * Type parameter can be specified to ensure values under comparison have the same type.
 *
 * @example
 * ```ts
 * import { assertArrayIncludes } from "https://deno.land/std@$STD_VERSION/testing/asserts.ts";
 *
 * assertArrayIncludes<number>([1, 2], [2])
 * ```
 */
export function assertArrayIncludes<T>(
  actual: ArrayLike<T>,
  expected: ArrayLike<T>,
  msg?: string,
) {
  const missing: unknown[] = [];
  for (let i = 0; i < expected.length; i++) {
    let found = false;
    for (let j = 0; j < actual.length; j++) {
      if (equal(expected[i], actual[j])) {
        found = true;
        break;
      }
    }
    if (!found) {
      missing.push(expected[i]);
    }
  }
  if (missing.length === 0) {
    return;
  }

  const msgSuffix = msg ? `: ${msg}` : ".";
  msg = `Expected actual: "${format(actual)}" to include: "${
    format(expected)
  }"${msgSuffix}\nmissing: ${format(missing)}`;
  throw new AssertionError(msg);
}
```

☝️ Based on the implementation, [`ArrayLike`](https://github.com/microsoft/TypeScript/blob/v5.0.4/lib/lib.es5.d.ts#L1550-L1553) is definitely the appropriate type, although refactoring it to accept two [`Iterable`](https://github.com/microsoft/TypeScript/blob/v5.0.4/src/lib/es2015.iterable.d.ts#L30-L32) values would make it useful with more inputs... but that still doesn't solve the described "intuition" issue regarding `string`s being both `ArrayLike` and `Iterable`.

It would be a simple fix if TypeScript had negated types (e.g. `Not<Iterable<unknown>, string>`), but [that's not the case](https://github.com/microsoft/TypeScript/issues/4196). (Maybe one day!)

> Is it an option to fix this by changing the parameter types? `T[]` instead of `ArrayLike<T>` for example?

That would be a breaking change, but perhaps it's what was originally intended considering the function name? They should be `readonly` array types (e.g. `readonly T[]`) if that change is made.

**Comment by lionel-rowe** [comment]
How about this?

```ts
declare function assertArrayIncludes<T, Expected extends ArrayLike<T> = ArrayLike<T>>(
  actual: ArrayLike<T>,
  expected: Expected extends T ? never : Expected,
  msg?: string,
): void;

assertArrayIncludes(['a'], ['a']); // ok
assertArrayIncludes(['a'], 'a');
//                         ^^^ Argument of type 'string' is not assignable to parameter of type 'never'.
assertArrayIncludes('a', 'a');
//                       ^^^ Argument of type 'string' is not assignable to parameter of type 'never'.
```

[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMBBGGKATwEl0JlRCAeAFQBp4BRADwAO4DCGDwQfEamCF4lajQAyWANYgOAPngBeOVVrK1mjQAoAUPAKZkUCAC49Cw+vYbOF8YOGiH-IZlFPKRl4dngAfnhUEAA3UnhfLwDgd0sAW0IAc3CHQgwYLFRM9wBKBxicLGAAbjMzIhIyeVoGSGYQQhMAbQByKB6AXW5e-oGS2obSCn16RnbOkcHuPp7x+uIp5tm2lhMV5f61oA)

It's still not 100% ideal IMO, as I'd still expect `assertArrayIncludes(a, b)` to be analogous to `a.includes(b)`, but at least it clearly indicates something's wrong before runtime.

You could even get more intuitive error messages with something like the following, although it is a pretty gross hack:

```ts
namespace Never {
  declare const IsArrayLike: unique symbol;
  export type ArrayLike<_> = { [IsArrayLike]: never };
}

declare function assertArrayIncludes<T, Expected extends ArrayLike<T> = ArrayLike<T>>(
  actual: ArrayLike<T>,
  expected: Expected extends T ? Never.ArrayLike<T> : Expected,
  msg?: string,
): void;

assertArrayIncludes(['a'], ['a']); // ok
assertArrayIncludes(['a'], 'b');
//                         ^^^ Argument of type 'string' is not assignable to parameter of type 'ArrayLike<string>'.
assertArrayIncludes('a', 'b');
//                       ^^^ Argument of type 'string' is not assignable to parameter of type 'ArrayLike<string>'.
```

[Playground](https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEA5CA3CAnJBvAUEkgCYTwA2IWy8A9sFAC5ICSUAglliAJ4AyASwDWEAFxIArsAEBHCcig8wAI1rkA3ISQQAHjFpZmjHjGSdu-YRAA8AfQB8SALx4kAbTbnegkQF1xwBjYSAC+miH4+KQUVMgAZlLwjAL0SCBQUNiMXjwswBQSpFDWACoANEgAonpkjBDE2jp1wMRQSDk+NiWOLh1Wpfb2ABRaCIwSIOTifSIDZVq6pkn14tVLdQ26za1IJUgA-KhBWAB0M12OqzXLxPNEYFAA5vviTFgCwI-zAJTi6LQCYiafDpTKGHJ5ApFIZuADkIFhvgqcIRvm+mlBWQh+XIhWgMPhiIqsOUsPRIIyWK4vEhuOhhOJpPJQA)

**Comment by 0f-0b** [comment]
What about `object & ArrayLike<T>`?

```ts
declare function assertArrayIncludes<T>(
  actual: object & ArrayLike<T>,
  expected: object & ArrayLike<T>,
  msg?: string,
): void;

assertArrayIncludes(["a"], ["a"]);

// Argument of type 'string' is not assignable to parameter of type 'object & ArrayLike<string>'.
//   Type 'string' is not assignable to type 'object'.
assertArrayIncludes(["a"], "a");

// Argument of type 'string' is not assignable to parameter of type 'object & ArrayLike<string>'.
assertArrayIncludes("a", "a");
```

**Comment by lionel-rowe** [comment]
> What about `object & ArrayLike<T>`?

Looks like a good option, although deno-lint warns about `object`:

> This type is tricky to use so should be avoided if possible
> Use `Record<string, unknown>` instead

But I think this is a valid use-case for `object`, and the warning can be easily suppressed:

```ts
// deno-lint-ignore ban-types
type ArrayLikeArg<T> = object & ArrayLike<T>;

declare function assertArrayIncludes<T>(
  actual: ArrayLikeArg<T>,
  expected: ArrayLikeArg<T>,
  msg?: string,
): void;

assertArrayIncludes(['a'], 'b');
//                         ^^^ Argument of type 'string' is not assignable to parameter of type 'ArrayLikeArg<string>'. Type 'string' is not assignable to type 'object'.
assertArrayIncludes('a', 'b');
//                  ^^^ Argument of type 'string' is not assignable to parameter of type 'ArrayLikeArg<string>'. Type 'string' is not assignable to type 'object'.
```

**Comment by iuioiua** [comment]
Having it be a `readonly T[]` seems like the right way to go. I'd be happy to look at a PR that implements that.

**Comment by lionel-rowe** [comment]
> Having it be a `readonly T[]` seems like the right way to go.

I tried that, but it breaks type checking for 1 existing test using `Uint8Array`s for both params, which seems like a valid use case. I've put up a PR using the `ArrayLike<T> & object` approach, which I don't think would break anything except code directly relying on the weird string behavior.

**Comment by jsejcksn** [comment]
Thinking more about this:

It appears that expectations are violated because the name of the function (`assertArrayIncludes`) doesn't align with the types of arguments that it accepts.

The implementation only requires values of type [`ArrayLike<unknown>`](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&noErrorTruncation=true#code/C4TwDgpgBAogHmAhgOwCYB4AqA+KBeKAbygG0BpKAS2SgGsIQB7AMykwF0AuN89qAXwDcAKFCQ2+WAhQYAggCd5iEABlK9dAFdktZIwDuybNhFQzAenMA9APzCgA), which have number-indexed members and a numeric `length` property:

```ts
type ArrayLike<T> = {
  readonly [x: number]: T;
  readonly length: number;
};
```

> I've put up a PR using the `ArrayLike<T> & object` approach…

If adjusting expectations isn't the solution, and we're thinking about narrowing the acceptable arguments to more closely align with the function name for the sake of intuition, shouldn't we be more explicit about the narrowed type?

If we want to accept "only arrays" and reject "other array-like values such as `string`", then a readonly type could be used which represents any array or typed array:

```ts
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray
type TypedArray =
  | Int8Array
  | Uint8Array
  | Uint8ClampedArray
  | Int16Array
  | Uint16Array
  | Int32Array
  | Uint32Array
  | Float32Array
  | Float64Array
  | BigInt64Array
  | BigUint64Array;

declare function assertArrayIncludes(
  actual: Readonly<unknown[] | TypedArray>,
  expected: Readonly<unknown[] | TypedArray>,
  msg?: string,
): void;
```

This will meet the expectations expressed earlier in this issue — the following statements produce this error:

> Argument of type 'string' is not assignable to parameter of type 'Readonly<TypedArray | unknown[]>'. (2345)

```ts
assertArrayIncludes("abc", "abc"); // Error 2345
//                  ~~~~~
assertArrayIncludes("abc", ["abc"]); // Error 2345
//                  ~~~~~
assertArrayIncludes(["abc"], "abc"); // Error 2345
//                           ~~~~~
```

The suggested changes above are non-breaking (the existing tests pass) and the generic parameter `T` is removed — I'm not sure why it was there in the first place since it's `unknown` in the implementation and is also never used.

[Here is a link to a TypeScript playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&noErrorTruncation=true#code/PTAEGEHsAcE8CcCWBzAFgF1AJgAwEYAOAWlywGZR1UBTUAEWoDtJQBDAVysngGcA6UAEEANsNBI06HuOo9q8AG7UAJgICyASQAqoYYgDGTOXwBQIUIgC20bpgDeoagEd2rMQF9QAM3iRLoACI+YGdXYT4pAIBuMzArG3h7b25LVkxPHz9A4IB9LxS0iJ5o2ItrW1AHQR45RMRIRgBReF94UAzffyDgVhr5dHrGHPlWopLzeIqHXtr0LVRfAHdpDqzuy0hVSJjlan1hVnhaL3ZGfQGGxxc3AAp9AC5QU4BrZkXGABpQZUeXt8YAJSPABGkEgwmorEYOz2ByO3lO50GyXgqXQNwUv0Yr0g7yBoB46CQjGQMP2h1o5JqQj6dQazVajgAHugmMppAzuJUTKBQPoGoT4OxztwbpZZDxWMhqI9BYgSQCYu4TLtyfCTmcLow2LS5gtcTwbjzvIxHjcAaAALwAPie2P+H2Nlh4yAA-LKifLkI78X9cdCVbCKQjNciZv15kseAAeRrM1mMdmgTltS3Jlrca1G3leU2gc1W21+96O3kp8AHGqPRjURb5vgNw7IHiPKGwADaAF0LTbk6XQM7kBozsJ2LseO6CZ6Sf3B5O5TOTPjGmS4ZSBZgGMxHg5WYSboxWOKPcTvSbHgA1SCIZQAMURWvxCmvynaMVKGHQ0BbIF2SmEMDyHwGwAF6IKIrB8NwyAhIwRAAKoAMrAMokD6DwwAAOrUMCwAAFKsAorCIfoSDQOgwAAErUF48hMIYwAAOIAcCbg5AA8sCABWexSMAWiwNAKiCC0rCwCY1BMgkmDoIJtACUJygifAYlWsaAA+oDDugBDKWJGmgPB8o6Xp4m8ppRmMDpFZHoppkGdpeAAGz2eZhnGc5rmgJp2lkFgXkWcZfkBaAt4AWkwWiWZ3mheF6BOQALCFABCKDaYlKUoJZ8VJVF77mJ+373CAyCIFQ7DAnw-KWChTDglCyi1cwOSEo1wIscAOB8LgBB8DgPS6gNsw5IcKmwDk8r7GOshFGYABUc08nNoBqKwzy0FCOqzMiVBpKAAAGrDnGE+0WCO03SFQtD7ZJQnnCop1EaOM1LVpXigMwMk0Nqm0jFyizgWIwK0FQSyMKYoCLZDoAKbQ0CHEe1Csm0+ibcDBJ3YgXiIColAsEY7Dwk97CyHauwo348NIDwlyoIRIM0ASiOUHJENQ8tAACkm2RCr37fzUivZMiSVFt-SmcOU3ju03idIEhU-k1kB8AcibAK1HMACSIVodA5BejSUYhGjsQAckN-QW4kI1RRN53jmMMSQ694aJBL9uyNGjDsJYwPwFm7Z4F8WCdl87YhwCfP80twASVJFQakilyu+g7tS7I2ZsMdbiPNRrCoYwwiwNGxaMF2MWw0pUXWv2t28SoueQgXRcl-a-rl5plemTXTouvO07eku3K8vyjCEgOiA1F6WI4u85dpl2TsovmEKYIgVqgDgUQWKA0bMndrKqBCJJUNviAANTnxadjGryq-JKcr5pl4bhyEvOZcjc99cRvW+gD-e8jroDCCrJgyBT7-0vtfW+vILDvRuKEW4dd7rKHbIgUOWdgFuHbFxbs0DYEEIfomDeRISbv0IcCI4a1yG8mVAQuhsCsb5gAIT5EfvgwhlhJ48C9HwaA7AeCoAQVJeuqD0GKhgQwhhTCxTcN4cfcBqArSWjTDgDhvIjjAPgAGWhJhjSj3HoORC7AvDYyZBvQcoBXQHUeJrOwg53CnUeEEEovJLFpn2o0ERKDMFhGcXY-IqI0g3CAWEAE7gAh4zOunfxN8CGBLRMIg+KhI60ICHYoxJizHuAADqMC4VPEkti7AJOCQUnhCpHFL1BriD6tYaTbXpBmeAYoXQSOVCYFOadRzjhuO2AIrBgT6ACBg-pgzhndm3uYdizxOm6m6RdG4AyhkBC+Ms4ZipQDmC8ck18skhJEH0DQfQzwvSOGaXM2YCzenrNWaAMZKzJlbLADs0RLMDlHL2Kckk5zWiXPFlFSWPSM4PImWs8ZARNnbO8Yfd51BDnHO+cgX53A9EFXQF+RWpVyqVWqkrVWjVdjNVasAdqkBcJdR6n1K2FEU42zGnbdOPAch7nQLNLcytWVLNMlAKyrB5TFC+InLU+YOEGMwGYrRtAF4BCJZAO5AREAgQVaOBQIyl7iu8IgFkhNqCcR4ucDe7YHByucaqyJ7gvgmrqs4vCxR2idiXl0wFHtDSSt1WHWVdURkSN5M6saQLFnuqOPq3iYdrXbkCOah1vqxZuxdUyzOvJsq6SinwTIlg+lB2wF8MgXwErdn7Mm4yqaxrps6Fm4OubC3GljSnSMBok2isLHG1OCbgVuu1VK0N5xw3fBtYEZguwLU1oIdURpTRmlFoOq8nxoSc6BHbMaOJsDTVRvYGq-slrl0wLXQEO1qzjTbs7JE9ALBJrAucUu3kK7eR7qHdQQ9tDHQntMOU6e9yd0EPvZsR9W6X37X7O0iRQA) which demonstrates the code above. I am initially sharing this here to solicit feedback before considering creating a PR. Thoughts?

Also, [here's a playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&noErrorTruncation=true#code/PTAEGEHsAcE8CcCWBzAFgF1AJgAwEYAOAWlywGZR1UBTUAEWoDtJQBDAVysngGcA6UAEEANsNBI06HuOo9q8AG7UAJgICyASQAqoYYgDGTOXwBQIUIgC20bpgDeoagEd2rMQF9QAM3iRLoACI+YGdXYT4pAIBuMzArG3h7b25LVkxPHz9A4IB9LxS0iJ5o2ItrW1AHQR45RMRIRgBReF94UAzffyDgVhr5dHrGHPlWopLzeIqHXtr0LVRfAHdpDqzuy0hVSJjlan1hVnhaL3ZGfQGGxxc3AAp9AC5QU4BrZkXGABpQZUeXt8YAJSPABGkEgwmorEYOz2ByO3lO50GyXgqXQNwUv0Yr0g7yBoB46CQjGQMP2h1o5JqQj6dQazVajgAHugmMppAzuJUTKBQPoGoT4OxztwbpZZDxWMhqI9BYgSQCYu4TLtyfCTmcLow2LS5gtcTwbjzvIxHjcAaAALwAPie2P+H2Nlh4yAA-LKifLkI78X9cdCVbCKQjNciZv15kseAAeRrM1mMdmgTltS3Jlrca1G3leU2gc1W21+96O3kp8AHGqPRjURb5vgNw7IHiPKGwADaAF0LTbk6XQM7kBozsJ2LseO6CZ6Sf3B5O5TOTPjGmS4ZSBZgGMxHg5WYSboxWOKPcTvSbHgA1SCIZQAMURWvxCmvynaMVKGHQ0BbIGQiCo7DAnw-KWMAuzMAciZgUwkA5ISyjAMCwiQMCwA4HwuAEHwOA9LquGzDkhzwKwsA5PK+xjrIRRmAAVDRPI0aAaisM8tBQjqszIlQaSgAABqw5xhLxFgjpR0hULQvHUEy0B7KyyjCQobjsFRDGgBoXigMwmASdq7EjFyiyIKIoDArQVBLIwpigPRNmgFosCyaA0CHEe1Csm0+jsWZBKyfoiBeIgKiUCwRjsPCSmjrIdq7J5fguUgPCXKgrBKJQNAEm5lCOdQ1m2YxAAC0lHtAEJqbxFVSGpkyJJUHH9IILQkcOFHju03idIEn7fvcIDgZAfCQQh8EFQAJAAylodA5BejQAErjRoADyABy+H9OtiSEU1pHkaO45jDENlqeGiSNcRsAtftsjRow7CWGZ8BZu2eBfFgnZfO270AuVFUMcAJjSQkmAakilyneg53NaJ47RloWbGgJ6BhI8UOwAAMogrFw9a-ZA3JKioztmPY-Ds4uvO07eku3K8vyjCEgOiA1F6WI4u8XZWqAXZHSi+YQpgiBczgUQWKA0bMn58mDUwyBUKLiAANSKxadjGryAvJKcr5pl4bhyLzOZcjcmsAFbC6L5sS0jYQyyS8ugKbyuq+rvIWJpNyhLc+PnCo7aIB9bCCW47am92Ltu5HWuJlzRIqYbUfAkcLEJ7yyqR+nbsBfmACE+TaxHUeWMzPBenw0DsDwqCezJBPKP73YJ5nmfZ2KJdlxC9uoFalppjghe8kcyPwAGacmMa9OM4O43sF4gVMlzg6gK6fGPKNdiDu4wmPEEJS8kvaa8Y0te+6+NtuDv6-5KiaQ3OfwgAu4AQhSJrUyoE6+u9faI11LKg-WnAI69p6z3nu4AAOowYuLMSRrzsN-W+0DS4Ki3rzCyuItK1hpJxekGZ4BihdIqEwyoPzoC-D+YAf4AJARAtBCCUIEL9TgugBCSEUJoQwjgLCOEIabXQNtC6ZEYayByHudA1EtwDTETcAIaMoCMHQKweUxQvigy1PmQuk8QaIBZOFWgaZ2wBH6gEL4AREAAC8TGBFHAoAInZeZaO8Do4e1AlrAlNnJLm7YHD9R3jY5+7gvg+JgjvAAUsUdo9jEa6jRldMSNx54uM+kYmCdiiG8ghrE4RhpEl6LcR484n1gnbmsewWxkT0n1TOjtOJ45sxuwAKrynQAQNGfBMiWBuC9N6XwyBfAACzdn7LyJpCjWk7XaZ0Lpr1sC9KGcaSpENIwGnqbyAsvZMk1OyQk5xeT3FySKd8EJgRmC7ACfMyO1QcFNDwcMvix8-5n2DsIHe7ZjRq0jr40ptj+yBPea7L5ARwkmONH8zsz90AsD2pRV5-zPnHICKc6gIK06OnBaYJBrNuZwrdoCpFKL2hot4v2Ih7giFAA) to the unmodified code from `std@0.208.0` in case anyone wants to experiment.
