### ISSUE TITLE
very strongly typed `collections/` functions

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#3384]
**Is your feature request related to a problem? Please describe.**

return type of some of the functions of `collections/` functions can be inferred in compile time.
inspiration: 
- https://github.com/dilan-dio4/strz
- https://github.com/type-challenges/type-challenges

**Describe the solution you'd like**

for example, return type of distinct can be improved with:

```ts
type Arr = readonly unknown[]

type Distinct<T extends Arr, Rest extends Arr = []> 
    = T extends readonly [infer Head, ...infer Tail]
        ? Distinct<Tail, Head extends Rest[number] ? Rest : [...Rest, Head]>
        : Rest

function distinct<const T extends Arr>(array: T): Distinct<T> {
    const set = new Set(array);
    return Array.from(set) as Distinct<T>;
}

const d = distinct([1, 1, 1, 2, 'abc', 'abc', 2, 3]) // [1, 2, "abc", 3]
console.log(d) // [1, 2, "abc", 3]
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTnKBeKcIEMAmB7AdgGxCgFdcBrXbAd1wG0BdAKEdEigBEBLAZ2E9wDGwADwAVKBAAewCLkzdYCADRQAShF4Tps+YsQoGAPiiMoZ5FHFSZchWix5CUWvwBmERAAkMmFQDoAtw9LdE58JnNIqAB+Dh4+QRFRUPwVbywtG111XlpcYgBbACMPehi1DWAoAC5nAL8c4DSfekNTKLNaxuZXUiFOPChMeP4hYQE8TSttWz1DAAp0BHQQWtEASlquXlGk4wBvdrMJ3E1uCCqUXAgqKABlC8XlkHWAbiPUC+I4XD0Vv1ccGwBXm52A6yg6AU2wSY1EhneAF9mCdNJgLMMdol5rQAIwqfFQQkAJhUAHJ0EUBGTyZTqSpSVAAMz0CEAejZzhJKgARHSeSoWYxUdh8BA-PhsABzeaYdmcvEM3n8wX0IA)

**Comment by scarf005** [comment]
yes. type definitions needs more polishing, however. for example, putting non-readonly array will result in `[]` for return type when it should be `T[]`

**Comment by jsejcksn** [comment]
@scarf005 I think the idea itself has merit, but the types and type utilities need to be very carefully considered and tested on a large variety of inputs and contrived edge cases.

Using the code you provided as an example: it works with the primitives shown, but when object-type values are elements in the input array, you can see bugs appear, because — for one — TypeScript's [`extends`](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) keyword is not the same as JavaScript's [same-value-zero equality algorithm](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#value_equality) used by `Set` instances:

[Forked TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTnKBeKcIEMAmB7AdgGxCgFdcBrXbAd1wG0BdAbgChnRIoARASwGdhuuAMbAAPABUoEAB7AIuTL1gIANFABKEflNnzFyxCgYA+ZlGRRJMuQqVoseQlFqCAZhEQAJDJjUA6ALcPS3RufHozcygAfi4+AWExcVD8NW8sHRt9TX5aXGIAWwAjD3oYjS1gKAAuZwC-HOA0n3pTKJqK-hZmV1IRbjwoTHjBEVEhPG0rXVsDYwAKdAR0EFrxAEpann5RpOMoAG9IidxtXggqlFwIKigAZQvF5ZB1lnM0YGI4XAMVv1c4NgCvNzsB1lB0EptgkxuJjCwAL6sE7aTAWYY7RLzWgHCG1ACMUARalx6AJRJJeKg+LURVqACYifRXpFzAB6NkAPWiyMm2HwED8+GwAHN5phXlAOc5SeTiYcqYT5bLqbSGUzmEA)

```ts
const d = distinct([{ a: 1 }, { a: 1 }, { a: 1, b: 2 }]);
    //^? const d: [{ readonly a: 1; }]

console.log(d); // [{ a: 1 }, { a: 1 }, { a: 1, b: 2 }]
```

The result objects are also not readonly, etc. It's essential that types accurately represent the runtime values.

Some type testing utilities already exist in `std` at https://github.com/denoland/deno_std/blob/main/testing/types.ts — you might find them useful in your development if you pursue this.

**Comment by kt3k** [comment]
Though we are open to new type improvement suggestions to `std/collections`, I'm closing this one as there's no particular action is possible about this for now
