### ISSUE TITLE
Snapshots break after Deno 1.33.2

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno_std#3404]
**Describe the bug**
Deno 1.33.2 changed the way to serialize multiline strings and, instead of a single string, it returns a concatenation of several strings, one per line. This makes all tests to fail: 

![imaxe](https://github.com/denoland/deno_std/assets/377873/813cd8f7-b8aa-4776-96c2-3dce3af8253d)

**Steps to Reproduce**

1. Create a snapshot in Deno < 1.33.2
2. Upgrade to Deno >= 1.33.2
3. Run the tests

**Expected behavior**

The solution is update the snapshots with `-- --update` (obviously), but I think the previous format was much clearer to see the difference between two snapshots.

**Environment**

- OS: All
- deno version: >= 1.33.2
- std version: 0.186.0

**Comment by kt3k** [comment]
I agree that the previous version was better for comparing snapshots.

This was caused by this change in Deno CLI https://github.com/denoland/deno/pull/18691 (We aligned `Deno.inspect` behavior to `util.inspect` of Node.js to reduce the duplications)

@crowlKats Do you know if there's any option to restore the previous behavior for long string values? Or the previous behavior is gone now?
