### ISSUE TITLE
Clean up `bytes` module

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3549]
Most APIs of bytes module are simple functions that work on Uint8Arrays, but only `BytesList` has exceptional design and purpose.

`BytesList` was introduced for optimizing `readDelim` method of `io` (then `bufio`) module. https://github.com/denoland/deno_std/pull/867 It was more like internal utility for optimization rather than a public API.

I think we should deprecate this API before stabilizing `std/bytes` (but we might better to check the actual usages in the ecosystem)

part of #3489

**Comment by lino-levan** [comment]
I use `BytesList` quite a lot as it's a pretty nice way of doing operations on a group of `Uint8Array`s. I'm not sure I support deprecating it.

**Comment by kt3k** [comment]
@lino-levan Could you share your use cases?

**Comment by lino-levan** [comment]
I use it a lot for efficient encoding. It doesn't look super used in the ecosystem outside of some of my repos and [iuioiua's r2d2](https://github.com/iuioiua/r2d2/blob/c0688b37e58b99106e86ce9796eae00d782060c1/mod.ts#L46), but maybe that's just due to it's nature. I'm for keeping this around.

**Comment by iuioiua** [comment]
I used `std/bytes` because it's 50% faster than web streams. See: https://gist.github.com/iuioiua/f1b93f1b7e3c1a055ddf6fc60a6743a2

**Comment by iuioiua** [comment]
I only use `BytesList` for concatenating `Uint8Array`s. According to benchmarks, `BytesList` and `concat()` are pretty much on par with performance. In fact, I'll make the switch to using `concat()` irrespective of whether `ByteList` gets deprecated.

I prefer functions over classes and methods because they're simpler. I'm +1 for deprecating `BytesList`. My main concern would be: For each `BytesList` method, what must a dev use instead if `BytesList` were to be deprecated?

**Comment by johnspurlock** [comment]
Heads up - this seems to have broken `DelimiterStream`: see https://github.com/denoland/deno_std/issues/3609
