### ISSUE TITLE
Feature: something like Cheerio

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno_std#355]
It'll be awesome to have a web data mining tool like Cheerio in Deno. Cheerio is something like server-side jQuery

**Comment by zekth** [comment]
ref: https://github.com/cheeriojs/cheerio

@sh7dm please consider add links for examples.

**Comment by j-f1** [comment]
I’d suggest that given the increasing capabilities of the native DOM APIs and Deno’s philosophy of sticking to the standards, using or porting [`jsdom`](https://github.com/jsdom/jsdom) seems wiser. It seems like it can already run in a web worker, so it would probably do fine in Deno if wrapped in an ES Module wrapper.

**Comment by kitsonk** [comment]
Porting jsdom would be a nightmare.  It is huge and complex and has to be tightly coupled to Node.js at several levels.  On top of that, the DOM APIs for querying are really not as usable as they should have, which is why things like jQuery came along in the first place.  Given that, jQuery has a lot of baggage and I wouldn't consider it a modern API for querying DOM strings either.

That doesn't mean that some sort of DOM string querying tool would be useful, but I wouldn't want to use even something like cheerio.  Any of the virtual DOM implementations would be a lot better and they are much better abstractions to the DOM.

I think generally though we should be talking about specific use cases and not just go and try to implement any sort of idea, like a bird collecting shiny objects.

**Comment by jimmywarting** [comment]
> That doesn't mean that some sort of DOM string querying tool would be useful.

I find the browsers devtools `$$(selector)` to be somewhat useful. 
It's a shorthand for `document.querySelectorAll`
