### ISSUE TITLE
Deprecate `io` module

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3552]
APIs in `io` are based on the legacy Reader/Writer interfaces. We should deprecate `io` before stabilizing std.

part of #3489

**Comment by iuioiua** [comment]
Are web-streams-equivalent solutions on par with the performance of `Reader`/`Writer` solutions? If not, users can expect a performance hit due to this deprecation. Last time I checked, a [web streams version of x/r2d2 would be slower than the `Reader`/`Writer`](https://github.com/denoland/deno/issues/16314), though not majorly.
