### ISSUE TITLE
Clean up `collections` module

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#3599]
Most APIs in `collections` are simple functions inspired by lodash or kotlin.collectioins. However the following 5 classes are very different in design and purpose.

- BinaryHeap
- BinarySearchNode
- BinarySearchTree
- RedBlackNode
- RedBlackTree

I think we should move them under `std/collections/unstable` directory for now before stabilizing it, and keep considering the more appropriate way to expose them as public APIs.

part of #3489

**Comment by lino-levan** [comment]
Supplying a BST feels weird because it's almost never advisable to use one in real scenarios. Non-self-balancing trees are inevitably just going to be slower. Supplying an RBT feels weird because while red-black trees are an option for self-balancing BSTs, why even specify the internal mechanism? We should be free to change the internal workings of a self-balancing BST without fear that someone is relying on that structure (+ according to some research, it may actually have a slower runtime than the easier to implement AVL trees).

Implementing this in JS is probably not the right move here. Objects would probably be faster than JS implemented BSTs. I'm in favor of deprecating those APIs.

BinaryHeap does make a little more sense to me, but this should really just be exposed under a "priority queue" API and not as the raw data structure.

**Comment by KyleJune** [comment]
> Supplying a BST feels weird because it's almost never advisable to use one in real scenarios. Non-self-balancing trees are inevitably just going to be slower. Supplying an RBT feels weird because while red-black trees are an option for self-balancing BSTs, why even specify the internal mechanism? We should be free to change the internal workings of a self-balancing BST without fear that someone is relying on that structure.

The point of having it was so that RedBlackTree and other trees could be created from it. How it's implemented shouldn't really impact users of it. And if their is a major change made to it that would impact extensions of it, they could either be adapted in the same way we adapt RedBlackTree or they could keep using the old implementation. This is not a big problem.

> (+ according to some research, it may actually have a slower runtime than the easier to implement AVL trees).

AVL Trees are more strictly balanced than Red-Black Trees, so they can provide faster lookups. Red-Black Trees require fewer rotations than AVL Trees, so they can provide faster insertions and removal operations. Which is better depends on your usecase and both can be created by extending BinarySearchTree.

The reason I added RedBlackTree was for use in std/testing/time.ts, it uses the RedBlackTree for storing timers so that it can accurately simulate real timers which I believe also use a RedBlackTree. I never implemented an AVLTree because I didn't need one. I think it would make sense to add one though since both RedBlackTrees and AVLTrees are common/useful data structures.

> Implementing this in JS is probably not the right move here. Objects would probably be faster than JS implemented BSTs. I'm in favor of deprecating those APIs.

What does that mean, being an object rather than being implemented in JS?

> BinaryHeap does make a little more sense to me, but this should really just be exposed under a "priority queue" API and not as the raw data structure.

Rust has a BinaryHeap in their std::collections. That's why I went with that name instead of PriorityQueue.

https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html

**Comment by KyleJune** [comment]
> Most APIs in `collections` are simple functions inspired by lodash or kotlin.collections. However the following 5 classes are very different in design and purpose.
> 
>     * BinaryHeap
> 
>     * BinarySearchNode
> 
>     * BinarySearchTree
> 
>     * RedBlackNode
> 
>     * RedBlackTree
> 
> 
> I think we should move them under `std/collections/unstable` directory for now before stabilizing it, and keep considering the more appropriate way to expose them as public APIs.

I thought collections would be a good place since Rust also puts their BinaryHeap in it's std::collections. Another option would be to create std/datastructures or std/util. Java puts their data structures like Deque and PriorityQueue in java.util.

**Comment by lino-levan** [comment]
Thanks for the clarification Kyle. 
> What does that mean, being an object rather than being implemented in JS?

My main argument against RBTs is that there doesn't seem to be a usecase. If you wanted something like a key-value store, Deno comes with that OOTB. I am not aware of a situation in which using an RBT is needed over an object or a `Map`. Behind the scenes, they're usually all implemented by trees anyways.

> Rust has a BinaryHeap in their std::collections. That's why I went with that name instead of PriorityQueue.

That makes sense. I don't have anything against BinaryHeap as a concept, though I think the name is not descriptive of the API.

**Comment by KyleJune** [comment]
> > What does that mean, being an object rather than being implemented in JS?
> 
> My main argument against RBTs is that there doesn't seem to be a usecase. If you wanted something like a key-value store, Deno comes with that OOTB. I am not aware of a situation in which using an RBT is needed over an object or a `Map`. Behind the scenes, they're usually all implemented by trees anyways.

A Map and Object's keys would be ordered by insertion, the keys are not sorted. A RedBlackTree is ordered which makes it more efficient for iterating over the values stored in it. That's why std/testing/time.ts uses it, the timers can be added in any order via setTimeout and setInterval, then it can get the values out in order efficiently.

Deno KV is good if you need a distributed persistent store, but that doesn't make Map or RedBlackTree useless.

> > Rust has a BinaryHeap in their std::collections. That's why I went with that name instead of PriorityQueue.
> 
> That makes sense. I don't have anything against BinaryHeap as a concept, though I think the name is not descriptive of the API.

I'd have no issue renaming it if it would help with discoverability. Although I think the current name is fine.
