### ISSUE TITLE
Wrong normalization of unix-style paths 

### ISSUE THREAD

**Issue by Nautigsam** [denoland/deno_std#384]
I have the following code:

```javascript
import * as path from "https://deno.land/std/fs/path/mod.ts";

console.log(path.normalize("file:///tmp/toto"));
```
I get the following output:
```
file:/tmp/toto
```
I think the output should rather be like:
```
/tmp/toto
```

**Comment by zhmushan** [comment]
NOT WRONG
> The `path.normalize()` method normalizes the given path, resolving '..' and '.' segments.
So output `file:/tmp/toto` is as expected

**Comment by hayd** [comment]
@zhmushan  why does /// become / ?

**Comment by zhmushan** [comment]
> @zhmushan why does /// become / ?

Uh....
"///" is not a "normal path". It’s like "foo//bar" will be normalize as "foo/bar".
You can think of "file" as a volume, like "c:/" in windows.

**Comment by thgh** [comment]
You cannot always collapse multiple slashes: for example:`https://` is not `https:/`

Chrome normalizes `/Users/thomas/` to `file:///Users/thomas`

<img width="241" alt="screenshot 2019-02-08 at 15 55 07" src="https://user-images.githubusercontent.com/1109982/52485784-eefccd80-2bb9-11e9-861a-5d8fa5ffb258.png">

which makes sense when reasoning about urls instead of paths.

**Comment by zhmushan** [comment]
@thgh you should use URL API instead of path

**Comment by Nautigsam** [comment]
@zhmushan That's what I ended up with: `new Url("file:///tmp/toto").pathname`.
