### ISSUE TITLE
Discussion(semver): Necessity of `Comparator`

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#4047]
## Background

ref: https://github.com/denoland/deno_std/pull/4037#pullrequestreview-1797976465, https://github.com/denoland/deno_std/pull/4037#issuecomment-1871622745

This issue explores, if `Comparator` is necessary in the `semver` module.

@kt3k What made you think that `Comparator` might not be necessary?

**Comment by kt3k** [comment]
Comparator looks like an internal utility interface. It is very limited version of `SemVerRange`. I think the users are usually interested in working with `SemVerRange`s and not `Comparator`s.

`Comparator` still needs to be exposed as a public type because it's part of public `SemVerRange`, but I think the users are not interested in APIs which accepts/outputs comparators (e.g. `parseComparator`, `testComparator`)

**Comment by timreichen** [comment]
I agree. `Comparator` is probably not very useful as part of the public api. I think we should remove it from the public api.
However, working with `SemVerRange` directly is kinda clunky because
- it has an obsolete `ranges` property
- it represents an array of arrays of `Comparators`
That might not be a problem when using `parseRange`, but it is when using objects. Creating a simple Range is a bit awkward:
```ts
const simpleRange = { ranges: [ [ { operator: "=", semver: { major: 1, minor: 2, patch: 3 } } ] ] }
```
We might need to find a good solution to simplify usage. (related: https://github.com/denoland/deno_std/issues/3967)

**Comment by timreichen** [comment]
Ok, I will go forward and create a PR to deprecate all public `Comparator` functions and types.

**Comment by iuioiua** [comment]
Completed in #4131.
