### ISSUE TITLE
import typescript into deno_std

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#428]
Yes, it's built into deno, but it's difficult to access from the special snapshot where it's stored.

It would be nice to have access to typescript in 3rd party code. So the easy solution is to just import it in here.

**Comment by kitsonk** [comment]
@ry and talked about this... it makes sense... largely we need a CompilerHost that works well under Deno, which would be similar to what we use in the built in Deno compiler (possibly to become _the_ host).

I am going to be taking a look at it, but anyone else wanting to help would be glad to talk about what needs to be done.

**Comment by ry** [comment]
As a very first pass, I think just having a test that loads TS and checked the version (or some other basic thing) would be sufficient.

**Comment by kitsonk** [comment]
For anyone interested, the "trick" is that `typescript.js` loads in two ways, either as CommonJS or as global (see: microsoft/TypeScript#32949).  Because it does not detect what it needs for CommonJS it creates a global variable `ts` when loaded.

So we need to combine the `@deno_types` directive and also import `typescript.js` and scope the type definitions in the global scope (similar to what we do in `deno/deno_typescript/globals.d.ts` or `deno/js/ts_global.d.ts`).

So something like this:

```ts
// @deno-types="./vendor/typescript.d.ts"
import "./vendor/typescript.js";

import * as ts_ from "./vendor/typescript.d.ts";

declare global {
  namespace ts {
    export = ts_;
  }
}
```

**Comment by kitsonk** [comment]
@ry I have it mostly working with the following (with the couple recent patches I made to deno master):

```ts
// @deno-types="./vendor/typescript.d.ts"
import "./vendor/typescript.js";

import * as ts_ from "./vendor/typescript.d.ts";

declare global {
    // eslint-disable-next-line @typescript-eslint/no-namespace
    namespace ts {
        // @ts-ignore
        export = ts_;
    }
}
```

But the problem is that we load everything as a module into the isolate at runtime, which means that the global `ts` variable is created only in the scope of the module.  Unlike prettier, which properly detects that it isn't being loaded as a CommonJS or AMD module and defaults to exposing itself as a global variable, TypeScript only detects CommonJS otherwise just keeps itself scoped.  I already opened microsoft/TypeScript#32949 which would fix this properly, but it seems like the only real choice I have is to postpend to `vendor/typescript.js` something that properly lifts it into the global scope.
