### ISSUE TITLE
question(log): public methods in classes

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#4392]
**Is your feature request related to a problem? Please describe.**

There seem to be a lot of public methods in classes that might ought to be private or protected:
- `BaseHandler`
  - [ ] `log()`
- `ConsoleHandler`
  - [ ]  `applyColors()`
- `FileHandler`
  - [ ]  `flush()`
- `RotatingFileHandler`  
  -  [ ] `rotateLogFiles()`
- `Logger`
  - [ ] `asString()`

Is this by design or unintentional?

**Describe the solution you'd like**

Make them private or protected.

**Describe alternatives you've considered**

Leave as is.

**Comment by iuioiua** [comment]
I agree with all of these points. My understanding and reasoning is:
1. `BaseHandler.log()` doesn't even need to exist for the same reasons that the other logging methods (i.e. `warn()`, etc.) don't exist. That should be left up to the classes that extend `BaseHandler` for consistency.
2. `ConsoleHandler.applyColors()` seems to be only being used internally in `.format()`.
3. The user should use `FileHandler.destroy()` instead of `FileHandler.flush()`.
4. I don't see a reason why a user would need to manually call `RotatingFileHandler.rotateLogFiles()` as this is automatically taken care of while using `.log()`.
5. There doesn't seem to be a use case for `Logger.asString()` as part of the public API.
