### ISSUE TITLE
url: when passed argument is not a valid url, error throwed.

### ISSUE THREAD

**Issue by familyboat** [denoland/deno_std#5202]
Code snippet:
```ts
import {basename} from '@std/url';

// Learn more at https://deno.land/manual/examples/module_metadata#concepts
if (import.meta.main) {
 const invalidUrl = '/path/to/your/file';
 basename(invalidUrl);
}
```
When you run above code, error throwed.
You can get more information in https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by familyboat** [comment]
This issue is prevalent in the URL module, yet there is no mention of it in the documentation. Perhaps we could improve the documentation, or we might consider narrowing the range of acceptable input parameters.

**Comment by iuioiua** [comment]
The `@std/url` package handles [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)s, not paths. This is expected behavior. I think you're looking for [`basename()`](https://jsr.io/@std/path/doc/basename/~/basename) from [`@std/path`](https://jsr.io/@std/path).

I'll close this issue. Please feel free to re-open if you feel there's a need.

**Comment by familyboat** [comment]
I agree with the point you mentioned; users also have the responsibility to ensure they are using the corresponding features as required.
I am just a bit excited and looking forward to the upcoming stable version, and I have done some checks to the best of my ability.
Your work is highly valuable.
