### ISSUE TITLE
[http] Support for HTTP gzip compression

### ISSUE THREAD

**Issue by Mark1626** [denoland/deno_std#588]
It would be nice for `deno` to support HTTP compression. It could be enabled as

```ts
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve("0.0.0.0:8000", {compression: true});
```

**Comment by kitsonk** [comment]
This is likely a higher order concern, something that someone would build on top of the server.

**Comment by zekth** [comment]
> This is likely a higher order concern, something that someone would build on top of the server.

I agree. This is mostly handled by nginx or apache. Adding this layer to the deno server is not really mandatory. At least in `deno_std`

**Comment by sholladay** [comment]
I think compression absolutely belongs in `deno_std`, given that almost all web servers are going to want it. But I agree it should not be part of `server`. It should just be a separate thing within `deno_std`, which framework authors have to add on top of `server`. That's how it works in Node - there's a `zlib` module which provides the compression functions.

In Deno, I imagine GZip would be imported like this:

```js
import gzip from "https://deno.land/std/zlib/gzip.ts";
```

**Comment by zekth** [comment]
> But I agree it should not be part of `server`

Agree. Also maybe implement a `compression` module like it's done in Golang:
https://golang.org/pkg/compress/gzip/

**Comment by kitsonk** [comment]
JavaScript implementations of gzip are going to be silly slow.  This really treads into space where native modules would be helpful on Deno.  But at the moment I see two choices:

- We had compression op to Deno, which means technically it is part of core instead of std.  It should support gzip and brotli at a minimum.
- We look at ruggadising WASM support in std.  Something like https://github.com/drbh/wasm-flate is actually written in Rust and transpiled to WASM.  While it might be a bit "silly" to do this, it might actually make sense for Deno in the long run to have ruggadised support for Rust -> WASM for running modules that need a level of high performance.

(For the record, we utilise part of [source-map](https://github.com/mozilla/source-map/) which was moved to being authored in Rust and is transpiled to WASM.  We are using the Rust version directly for remapping our source maps on the privileged side)

**Comment by cdimitroulas** [comment]
I noticed that @arcatdmz who is a contributor here has been working on a deno port of `pako` which is a JS port of `zlib` which is surprisingly fast. Perhaps it's worth looking at those benchmarks first before dismissing a javascript implementation for other options.

The original library can be found [here](https://github.com/nodeca/pako). The issue where I saw this contributor's work is https://github.com/denoland/deno_std/issues/376 for reference.

**Comment by 101arrowz** [comment]
It's true that JS implementations are not horribly slow, but the fastest current library, [fflate](https://github.com/101arrowz/fflate), is still slower than native Zlib by between 10% and 25%. WebAssembly is slower by around 30%. Pako is slower by 40-50%. See [this benchmark](https://github.com/denoland/deno/issues/4071#issuecomment-785220267) for an example.

Native bindings are a no-brainer.
