### ISSUE TITLE
file_server should render markdown

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#64]

**Comment by kevinkassimo** [comment]
I think since [marked](https://github.com/markedjs/marked/blob/master/lib/marked.js) supports browser we could probably use it instead of doing a custom implementation from scratch. However, I think we might need to host a forked version to slightly modify the IIFE around it to make it fit for Deno.

I'll work on that if this sounds right.

**Comment by ry** [comment]
Sure. Ideally we'd find some small TS implemented one, but that works too.

**Comment by kevinkassimo** [comment]
Got marked [ported](https://github.com/denolib/marked). However currently not able to run any existing tests on it, since the original tests depends on quite a few Node packages to run (especially html-differ). I'll see if I could extract some tests to ensure minimum guarantees...

**Comment by ry** [comment]
@kevinkassimo Nice!

**Comment by zekth** [comment]
We can start by porting `unit-tests` and progress granularly ? ref: https://github.com/markedjs/marked/blob/master/test/unit/marked-spec.js

If ported and tested do we add it to deno_std?

**Comment by kevinkassimo** [comment]
@zekth You can probably try adding unit tests here: https://github.com/denolib/marked
