### ISSUE TITLE
Proposal: std/mail , std/smtp

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno_std#645]
Hello there.

I think it would be nice to have `mail` or `smtp` or both in `std`. This is very necessary for many applications & really many things are involved in this kind of package including the security aspect so I think it's ideal for Deno to have something official in the `std` packages. 

Current implementations in GO std:
https://golang.org/pkg/net/mail/
https://golang.org/pkg/net/smtp/

**Comment by PodaruDragos** [comment]
Did this idea got abandoned all together ? SMTP is a nice thing to have. GO has it in their std.

**Comment by bartlomieju** [comment]
I'm open to having these modules in `deno_std`. If anyone wants to work on this, feel free to open a PR so we can discuss it in detail.

**Comment by halvardssm** [comment]
Hi @bartlomieju ! I was testing around with the mail parser, and I made two (relatively unfinished) branches, [one](https://github.com/halvardssm/deno_std/tree/feat/mail) to simply parse a straight forward email in text format, and [one](https://github.com/halvardssm/deno_std/tree/feat/mail_go) which is a port of the go std. I would be happy to properly sit down and finish either of the branches, but which route would be the preferred one from your side?

**Comment by gtamas** [comment]
@bartlomieju 
What's the status of this? I think I could help out with this one too.
What do you think about the code provided above? 

@halvardssm are you still working on this?

**Comment by halvardssm** [comment]
@gtamas I made two proofs of concept, but I am waiting for feedback from the maintainers to proceed with either one of them. I'd be happy to collaborate on this if you are interested.

**Comment by bartlomieju** [comment]
Apologies for late reply. We discussed this issue among the core team and we believe that these two modules shouldn't be in the standard library (at least not now), instead being developed as community/3rd party modules. 

The implementation of these modules would require a lot of work and potential bug fixing; and we feel like we might not be able to address potential problems/bugs in a timely manner due to other priority work (like `std/node`). So I would encourage you to develop these modules out-of-bands from `deno_std` for now.

I'm going to close this issue for now, but please feel free to keep commenting here.

**Comment by timreichen** [comment]
Some years have passed and I think this issue should be reopened. A Smtp implementation in deno std sounds very reasonable to me.
