### ISSUE TITLE
golang context in http server request handling

### ISSUE THREAD

**Issue by mitar** [denoland/deno_std#660]
Should deno provide something like golang's request `context`? To handle cases when request handling timeouts and should abort all related computations/promises which were spawn because of the initial request, instead of them continue running?

There is [this package](https://deno.land/x/context) but I think this should be part of the standard http server.

**Comment by bartlomieju** [comment]
I don't have a strong opinion either way. 

CCing @LionC @nayeemrmn @cmorten @kitsonk @AaronO

**Comment by kitsonk** [comment]
I think that is what frameworks are for.  We jettisoned `media_types` from `std` a long time ago because it was "too frameworky".

GoLang as different fundamentals around how HTTP requests are handled, in Deno, we have adopted the web standards of `Request` and `Response`.  While they are seperate, a pair is effectively a HTTP request's context, and then `Deno.serveHttp` provides a "context" of the `.request` and `.respondWith`.  The `std` HTTP Server is a fill to bridge between the _old_ and _new_ way of doing things.  Adding an opinionated "context" on top of that then becomes even more of a "framework" versus a building block.

So I would not be supportive.

**Comment by bartlomieju** [comment]
Thanks for opinion @kitsonk; I'm going to tentatively close this issue for now. I'll be happy to reopen if there are strong opinions in the other way.

**Comment by lucacasonato** [comment]
@kitsonk `context` in Golang is mostly an `AbortSignal`, not so much a general purpose context store (although it can be used for that too).

I think that answers the question though: if you want an `AbortSignal`, use `Request.signal` - that _should_ be wired up so that if a request is cancelled, it is cancelled. (I am not 100% confident this is wired up correctly right now though).
