### ISSUE TITLE
discussion: Make std/http use web standard FetchEvent

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_std#673]
_I know this is really late for such a change, but I think it's important to discuss and I think I can implement this in a couple of hours._

I propose to switch the server in `std/http` from using a proprietary `ServerRequest` (and `ServerResponse`, denoland/deno#4861) to use the web standard `FetchEvent`, `Request` and `Response` that is used by `fetch` and service workers (https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent).

This would mean that `Server` changes from a `AsyncIterableIterator<ServerRequest>` to a `AsyncIterableIterator<FetchEvent>`. This would slightly change the semantics of using `Server`, but it would reduce complexity and we would provide an interface that is web compatible and familiar to many web devs.

**Comment by nayeemrmn** [comment]
Raising this here because the design of the eventual built-in HTTP server is discussed in this issue.

I think we should go with a custom `RequestContext` over `FetchEvent` after all. `FetchEvent` inherits from `Event` and has all of these useless properties tied to `EventTarget::addEventListener()` and friends. We'd be using an async iterator API so I don't know know if we can correctly populate those -- at best it's really strange (and unprecedented?). I also can't see anything in `FetchEvent` other than `request` and `respondWith()` that makes sense in a true backend.

**Comment by fusionstrings** [comment]
I am looking forward for `FetchEvent` implementation for compatibility with browser APIs.

**Comment by kt3k** [comment]
Closing as https://github.com/denoland/deno_std/discussions/1034 has more detailed suggestions.
