### ISSUE TITLE
Consider adding a path class to the standard library

### ISSUE THREAD

**Issue by cjbassi** [denoland/deno_std#678]
Currently there is a path module in the Deno standard library, but it's not architectured in an OOP way and the functions are stringly typed. This is similar to how python used to do path operations with the `os` module, and then they replaced it with the pathlib module which works in a more object-oriented way with methods instead of functions and with a strongly typed path type. Rust also has a path module in the standard library and they ended up basing it on pythons pathlib module. Thanks!

**Comment by bartlomieju** [comment]
I think this is still desirable. If anyone is courageous enough to undertake it, please let me know.

**Comment by iuioiua** [comment]
By the lack of discussion in over a year, it appears as though this feature is not desired much in the community. Perhaps, this issue can be closed.

**Comment by lino-levan** [comment]
I agree with @iuioiua on this one. It doesn't seem like anyone really wants to pick this up.

**Comment by dsherret** [comment]
I wrote a path API for dax here: https://github.com/dsherret/dax#path-api (just released) -- we might consider moving this down to deno_std, but how we would get interop to work well between different versions of deno_std will be annoying with TypeScript. In dax this is ok because most people won't be using it in libraries and are end users writing scripts, but that's not the case for deno_std. Perhaps we will need to ensure the type is always assignable to past versions and that the interface remains quite stable—never do breaking changes on it and be really strict about what we include.

**Comment by lino-levan** [comment]
After some soul searching, I've decided that I'd be pretty for adding a path class. Dax's path class looks great (and quite similar to the rust version). My thinking is that we don't allow path classes as input anywhere since it seems like it'll be a problem for forward and backwards compatibility. Just use `.toString()`!

**Comment by jollytoad** [comment]
please don't turn a simple set of functions into a class, it's completely unnecessary, platforms can easily be separated using a module structure... https://github.com/denoland/deno_std/discussions/3553

**Comment by iuioiua** [comment]
I agree. Simple functions, like we have now, are better than a possible class-based solution. I'm -1 on this. Do you think we can finally close this issue off, @kt3k?

**Comment by kt3k** [comment]
Looks like there's no strong support on this. Let's close

**Comment by dsherret** [comment]
I created a `Path` class that's built on top of `@std/path@1` and `@std/fs@1` (extracted out from dax). It's available here: https://jsr.io/@david/path

Please provide feedback here: https://github.com/dsherret/path (also, please consider contributing docs with examples) -- I'd like to stabilize this to 1.0 soon once I can get feedback.
