### ISSUE TITLE
[ERROR]: Object is of type 'unknown' while parsing YAML string

### ISSUE THREAD

**Issue by shanilsasikumar** [denoland/deno_std#713]
When I tried the following example I got the YAML string as a JSON object.

```ts
const data = parse(`
foo: bar
baz:
  - qux
  - quux
`);

console.log(data);

// => { foo: "bar", baz: [ "qux", "quux" ] }
```

But when I try to access an object from the generated JSON response, The following error is throwing 

```ts
console.log(data.foo)
```

```
[ERROR]: Object is of type 'unknown'
```

**Comment by sno2** [comment]
The parsed data is of type `unknown` because it is a safe version of `any`.  Therefore, you must verify that you can do something on `data` before doing it.  I would suggest using optional chaining like `data?.foo` or you could obviously do an if statement that checks if `typeof data === "object"` is `true` and verify that `foo` is present on `data`.
