### ISSUE TITLE
Reorg

### ISSUE THREAD

**Issue by ry** [denoland/deno_std#76]
We've been adding code without much thought to the overall directory structure. I suggest the following renames:

```
//net/http.ts -> //http/mod.ts
//net/file_server.ts -> //http/file_server.ts

//net/bufio.ts -> //io/bufio.ts

//net/textproto.ts -> //textproto/mod.ts

//path/index.ts -> //fs/path.ts
//mkdirp/index.ts -> //fs/mkdirp.ts

//logging/index.ts -> //log/mod.ts

//flags/index.ts -> //flags/mod.ts

//colors/index.ts -> //colors/mod.ts
```
Along with the associated tests.

If you're worried about breaking existing code:
1) People should link to tagged releases of deno_std ... EG "https://deno.land/x/std@v0.2.4/net/http.ts" .. we do not make stability guarantees for master.
2) It's better to make these changes now, when deno_std is young than later.

**Comment by hayd** [comment]
Very much approve of this issue/cleanup but

Not a huge fan of "utils". What is the logic for putting datetime there? What else is a util?

**Comment by ry** [comment]
> `//datetime/mod.ts -> //utils/datetime.ts`

datetime is very small... seems to not deserve its own directory. I agree it seems odd. I will remove it frmo the list

**Comment by ry** [comment]
```
//net/bufio.ts -> //io/bufio.ts
//net/textproto.ts -> //io/textproto.ts
```
I've also updated the above list with these suggestions. It's a little odd to put `textproto.ts` into `io`.... but i think it's better than in `http/` ?

**Comment by keroxp** [comment]
Please let me express the opposite opinion. I understand we need some consistent style or rule about module file's naming. However, in my opinion, `mod.ts` can't be consistent because there can be directories with no `mod.ts` (e.g. `io` directory may not have `mod.ts` because there are relatively many separated files). Some developer may get confused no `mod.ts` exists.
If you plan to place mod.ts because of having less files in directory than others, I think it is better to place it on root directory with directory's name (`//textproto/mod.ts -> //textproto.ts`).
One another reason I counter is about test files . To follow style of the language that deno authors (including me) respect, It is easy to understand that codes and tests are flatly placed by same naming rule (adding `_test` postfix).
I worry about it beeing the strict standard of module file naming in deno after 10 years.

**Comment by kitsonk** [comment]
I believe a collection of modules, something we would put in `std` in a sub directory, should have a module named `mod.ts`, even if all it does is export the "public" API surface that is intended for that collection.  There needs to be a "default" place to go look.  Even if it is a loose collection of functions and classes broken up across modules, the then they should all be re-exported from `mod.ts`.

**Comment by keroxp** [comment]
Thank you for the opinion!

From style guid, I understand mod.ts was ported from Rust's unofficial module convention. I doesn't know much about Rust, so looked around some famous rust codes on Github.

Even in rust community, mod.rs (or lib.rs?) doesn't looks predominant idea for representing module entry file, for me. For example, ring, the famous crypto library, has decided to stop using mod.rs just 27 days ago (briansmith/ring@69cc075) because
mod.rs might not be sensible (commented).

As @kitsonk says, Some developer may need "default" entry file for modules. But Go doesn't have, but succeeding because of a type and module system designed based on URL-like. Thanks to the modern intelligent editor, importing classes, functions and constants is very easy today. The only thing developer must know is component name not entry file's url.

In my opinion, why the entry file that is composed of all internally exposed component from other files was needed, is classic programming languages couldn't import module directly from URL! (like ruby, python and npm do)

I believe deno's module system based on URL is pretty nice. If mod.ts were implicitly required, It means that mod.ts can be omitted.

On the other hand, I understand that It is difficult to create "package-private" (not desirable to be public) components in deno's module system. But that is ES/TS Module' problem. There must be another solution. Thanks!

**Comment by ry** [comment]
I think @keroxp makes a good point. I suggested mod.ts as an alternative to using index.ts - but a more minimal solution would be to simple tell people to avoid index.ts in the style guide.

**Comment by hayd** [comment]
Ring/that issue has a history, see https://github.com/briansmith/ring/issues/598.
Anyway this is just a style guide not rejecting certain configurations (as rust were).

We're also not talking about a mod.ts for each *file* which is what ring maintainer took exception to with mod.rs. In deno you can use relative imports trivially within a project.

ring still uses lib.rs which is what this is more analogous to imo. If there are several files a mod.ts exposing all of them is a reasonable and offers standard entry point to a public API for the repo. 

I'm very much in favor of this consistency (at least within std)

**Comment by keroxp** [comment]
Sure, I let it decided totally by @ry
But may I ask you more questions?

In deno_std,

- Should every sub(and sub)directories have `mod.ts` for default entry point?
- Should there be no module files on the root directory?
- Collecting public api to `mod.ts` means there are duplicated exportation on the project, is it desirable?
  - deno resolves "Aclass" from `https://deno.land/x/some/mod.ts`, 
  - `mod.ts` exports "Aclass" from "../aclass.ts"
  - deno downloads modules recursively, both `mod.ts` and `aclass.ts` will be downloaded.
  - As a result, there are two identical exportation about `Aclass` on `~/.deno/deps/https/deno.land/x/some`
  - Editor will show duplicate suggestions before importing because both are valid importing reference.
  - <img width="762" alt="2019-01-06 18 39 57" src="https://user-images.githubusercontent.com/927286/50734438-8a2d0c80-11e2-11e9-8288-435fd1f26183.png">
  - Ideally, `contentType` in `mime.ts` should be package-private in above case.
  - If can be, `mod.ts` is considered  as consistent....
  - `Go` does it by initial-based ACL 😩
- Frankly, I think it is not good idea to collect public api to one file, especially deno's module system even though it was good idea on other languages.

**Comment by kevinkassimo** [comment]
The duplicate suggestions part sounds more like a problem with the editor itself. It might be possible that the editor could prefer exports from `mod.ts` over those from other files (a simple reordering of suggestions sounds good enough for many use cases). (definitely not a good idea, but the editor could also possibly choose to ignore/gray out exports from file with names, say, starting with `_`, when a `mod.ts` is present in the same folder (when the user is not editing files inside that folder))

As to `mod.ts` for subdirectories, I don't think it would be that necessary unless we want to have public submodules. I deem `mod.ts` more or less serve just as a convenient entry point for users and a convention that could be changed if general feedback is against such design.

Also, I am somehow against package private design implemented by Deno but not present in ES/TS standards/proposals with positive feedbacks (opposite of things like `globalThis` which, as unhappy as I am with the naming, Deno should support it) Probably we could resort to namespaces at times?

**Comment by kitsonk** [comment]
> It might be possible that the editor could prefer exports from `mod.ts` over those from other files (a simple reordering of suggestions sounds good enough for many use cases).

I believe this is something that could be added to [deno_ls_plugin](https://github.com/kitsonk/deno_ls_plugin) fairly easily.  I think re-ordering (versus eliminating) would be best.

> As to `mod.ts` for subdirectories, I don't think it would be that necessary unless we want to have public submodules. I deem `mod.ts` more or less serve just as a convenient entry point for users and a convention that could be changed if general feedback is against such design.

I agree with this wholeheartedly.

**Comment by kevinkassimo** [comment]
@keroxp fyi extensionless support has been dropped in denoland/deno#1396 . As for other part of your argument, please give me more time to think about and I’ll reply later...

**Comment by keroxp** [comment]
@kevinkassimo  There seems to be unmerged reorg PR with `mod.ts` styles. and third party's libraries are starting to follow this style. So I  drop my proposal for speeding up. Keep going.

**Comment by kevinkassimo** [comment]
@keroxp I’m still collecting opinions on `mod.ts` from others I know. Since it is currently still at an early stage of adoption it should be easy to change if given more negative feedbacks

**Comment by tunnckoCore** [comment]
Hm, sorry but trying to keep up. Can we read somewhere about the `mod.ts` decision?
I don't see why `/index.ts` is not an option? If it's only because "it's shorter", that's not an argument to me, and definitely, don't like it. Why not think upfront for smooth transitioning by node.js folks or newcomers? Why should follow conventions or ideas from other languages such as Rust and Go, when we already have mostly 10 years of experience with Node.js and enough conventions and understandings?

Why not `main.ts`? This at least follows at some point more of the other languages. And it's a good word, making sense.

As for the automatic resolving,

> For example, if there could be importing like this:

I'm agree with @keroxp. In same time, I understand that it defeats the idea for URL based module system. Because one of the main ideas with Deno is to be as much as possible like in the browsers, except that it's in TypeScript.

**Comment by ry** [comment]
@tunnckoCore I wrote about it in the readme of this project:
```

index.ts comes with the wrong connotations - and main.ts should be reserved for executable programs. The filename mod.ts follows Rust’s convention, is shorter than index.ts, and doesn’t come with any preconceived notions about how it might work.
```

**Comment by kitsonk** [comment]
> In same time, I understand that it defeats the idea for URL based module system. Because one of the main ideas with Deno is to be as much as possible like in the browsers, except that it's in TypeScript. 

It isn't the browser the resolves `index.html`, it is the server that does it and tells the browser it is "such and such UI".  That non-explicit nature has _always_ caused issues.  So the decision was to _always_ try to be explicit, no magic and `index.html` implies that there is/will be some magic.

**Comment by kevinkassimo** [comment]
So there has been an alternative proposal that I have thought of in the past and brought up again recently during some discussions.

Since extensionless support has been dropped, there are no more conflicts between `log.ts` and `log/`. Thus it might be possible to adopt a directory structure like this:

```
- log.ts # External API are exported here. Uses or re-exports imports from log/mod_a.ts and log/mod_b.ts
- log/
  |_ mod_a.ts # internal code
  |_ mod_b.ts # internal code
```
With such directory layout, we could do
```ts
import "https://deno.land/x/std/log.ts";
```
instead of
```ts
import "https://deno.land/x/std/log/mod.ts";
```

There are some issues also with this approach. 
1. Ideally, it might be possible to import a module from registry by
```ts
import "https://deno.land/x/${module_name}.ts"
```
However, this requires the registry to extract `${module_name}` from the url and use it to decide how forwarding is done.
2. The directory structure might be messier with there are multiple submodules

Also cc @keroxp about this proposal

**Comment by hayd** [comment]
Is there a clever way to do this automagically, so that:

`https://deno.land/x/${module_name}.ts`

rendered a typescript file that imported and exported everything from 

`https://deno.land/x/${module_name}/mod.ts`

... without having to actually run any of the typescript on the registry server.

**Comment by kitsonk** [comment]
Generally "automagically" !== good idea... every time it bites you in the 🍑, that is the main justification for staying away from `index.ts`...  @kevinkassimo proposal isn't bad because it has no ✨🦄.

**Comment by hayd** [comment]
By "automagically" (silly word, I shouldn't have used it) I just meant populate `https://deno.land/x/${module_name}.ts`, nothing magical, and would be entirely within the registry.

**Comment by ry** [comment]
I'm maybe open to deno.land registry hacks like that but this discussion is more about the style guide for deno in general. 

1. I think we all agree that index.ts is a bad idea because it comes with the wrong connotations. 
2. We'd like to avoid a lot of module specifiers that look like this "/foo/bar/mod.ts" - it's a waste of space when "/foo/bar.ts" would work.
3. We'd also like to avoid a lot of module specifiers that look like "/foo/bar/bar.ts" - also a waste of space.
4. I'm hesitant to populate the root directory of deno_std with .ts files. It seems messy.

I feel like the ideal situation would be if we figured out some top level categories like "fs" and "net" that we could organize into? E.G.
```
//term/colors.ts
//fs/path.ts
//net/http.ts
```
