### ISSUE TITLE
feat(testing): Adding  something like `.not` in order to test opposite assertion.

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#816]
Adding something like `. Not` function in order to test the opposite assertion. Instead of adding new opposite function based on positive assertion like `assertNotStrictEquals` and `assertStrictEquals`.
This suggestion is inspired by [jest](https://jestjs.io/docs/expect#not).

**Comment by kitsonk** [comment]
I am not sure what this would offer above the existing APIs. I am not supportive.

**Comment by Songkeys** [comment]
For each positive assertion, we need to add a negative method *explicitly*. But with `not`, we only need to implement the positive. But it's too late to consider this pattern now I guess since the testing module has already got its own design.

**Comment by caspervonb** [comment]
I'm entirely sure this is actually needed, there are assertion libraries that offer assertions for everything under the sun but in practice I've found that I _generally_ only actually need the basics like, assert, assert_eq, assert_gt and assert_lt.

If we could narrow this down to specific cases, e.g assertNotEquals is needed because of these kinds of scenarios then that would be a much more concrete proposal and easier to evaluate.

**Comment by pavi2410** [comment]
As one use case: I require `assertStrictNotEquals` for testing if an array is cloned.

https://deno.land/x/xtend@v0.2.0/tests/array.test.js#L57
Obviously, this test case fails.

**Comment by aapoalas** [comment]
The under-work `expect` testing API will include this: https://github.com/denoland/deno_std/pull/3494

**Comment by kt3k** [comment]
No APIs in std use that pattern of chaining. Also there seem not enough attention to this suggestion. I think we don't want this design.

Having this kind of design with 'expect' (#3494) makes sense because the point of `testing/expect` is compatibility with jest, but `std/assert` is designed for Deno from scratch. So aligning the design to jest doesn't make much sense.

Let's close
