### ISSUE TITLE
std/encoding/csv.ts - `parse` and `stringify` should not require async code when data is already in memory

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#880]
Right now, the code in https://github.com/denoland/deno/blob/std/0.82.0/std/encoding/csv.ts forces the caller of `parse` and `stringify` to await the result, but there is no reason for these functions to be async when the object is already in memory.

**Comment by lowlighter** [comment]
All async code requirement seems to come from this single line:
https://github.com/denoland/deno_std/blob/3931030e7fae16158e3b6cb041a2a161c0cba6e3/encoding/csv.ts#L262

And from the function signature, it seems both `string` and `BufReader` are supported:
https://github.com/denoland/deno_std/blob/3931030e7fae16158e3b6cb041a2a161c0cba6e3/encoding/csv.ts#L392-L393

Not sure why we actually support `BufReader` (maybe because it was ported from Go?) but I think we should drop the support for it. With only strings as input it would be easier to make it synchronous.

YAML/TOML (and native JSON) libs only support strings as input so it would actually be more consistent

**Comment by MierenManz** [comment]
I want to pick up this issue. It seems like I only have the remove the `BufReader` input and the code related to that? I hope I understood that correctly tho

**Comment by MierenManz** [comment]
Anyone else can try if they want.
I don't got the time to pick up this issue.

**Comment by kt3k** [comment]
(Sorry for the late reply, but) I think async parse (with BufReader) might make sense if the source csv file is very big. That should reduce the memory usage and execution time.

**Comment by luk3skyw4lker** [comment]
I could take a look on that too, I'm already on the works of another issue envolving the same file. I'm just not sure if this is already resolved.

**Comment by lino-levan** [comment]
@kt3k This issue should probably be closed. `std/encoding/csv.ts` is no longer async and it also no longer supports `BufReader`.

Sanity check: https://deno.land/std@0.168.0/encoding/csv.ts?doc=&s=parse

**Comment by kt3k** [comment]
@lino-levan Thanks for the ping. Right, both are now sync. This issue should be now closed.

refs:
- `parse` became sync in https://github.com/denoland/deno_std/pull/2491
- `stringify` became sync in https://github.com/denoland/deno_std/pull/2611
