### ISSUE TITLE
assertArrayIncludes passes test if compare with an empty array

### ISSUE THREAD

**Issue by RivierGrullon** [denoland/deno_std#885]
This happens when I try to compare an empty array with the array i want to compare. 

```javascript

import * as assert from "https://deno.land/std@0.95.0/testing/asserts.ts"

Deno.test("test", function () : void {
    const fixture = ["deno", "iz", "luv"];
    assert.assertArrayIncludes(fixture, []);
})

```

https://user-images.githubusercontent.com/45011060/116504006-685d6500-a885-11eb-956e-e269375b4c4d.mp4

**Comment by sno2** [comment]
Currently looking into this, seems like it's a problem with the `equal` method used internally.

**Comment by sno2** [comment]
Isn't this working as intended?  `assertArrayIncludes` only checks if the first argument includes all of the elements present within the second element.  If you pass in an empty array into the second argument, then the first one would automatically contain all of the elements in the second array because there aren't any.

**Comment by MierenManz** [comment]
It should throw. There is nothing in the second array thus it doesn't include any of the items in the first array which means it didn't pass the test and should throw

**Comment by lucacasonato** [comment]
This looks like working as intended. The first argument is the _actual_ array (the bigger one), and the second one is the _expected_ one. The assert checks that all items in the second array are present in the first.
