### ISSUE TITLE
Export std/http/file_server functions

### ISSUE THREAD

**Issue by jsjoeio** [denoland/deno_std#898]
## Problem

As a user, I'd like to be able to use Deno's `file_server` in my project so that I don't have to write my own.

## Use case

I wrote a CLI in Deno and have an arg called "start" which starts a file server and serves static HTML content.

```shell
myCLI start

🚀 Starting file server on http:localhost:3000/
```

Serves static files from sub-directory:
```shell
/content/course.html
/content/index.html
/content/404.html
```

I installed the `file_server` after following the example in the [docs](https://deno.land/manual@v1.9.2/examples/file_server). It works really well! However, `file_server.ts` only exports `serveFile` and `serveDir` so I can't use it in my own project unless I rewrite the `main` function.

## Notes

~~I tried a couple static file servers from the community and didn't have a lot of success:~~
- ~~`oak` - [staticServer example returns 404](https://github.com/oakserver/oak/issues/307)~~

Related:
- [How can I use Deno's file_server in my app?](https://github.com/denoland/deno/discussions/10469)
- "`http/file_server.ts` has a lot of unexported functions in it that could be exported. I'd open an issue and detail your case there" [Discord conversation](https://discord.com/channels/684898665143206084/689420767620104201/838514485512765532)

**Comment by wperron** [comment]
I like how simple the file server currently is, so wherever we decide to go from here I'd be wary of changing the source code for it. However there are a lot of functions in there that have been stable for a while that are unexported that could allow the file server to be embedded or extended if they were exported.

For example [serveFile](https://deno.land/std@0.95.0/http/file_server.ts#L122) is exported, but [serveDir](https://deno.land/std@0.95.0/http/file_server.ts#L147) isn't. [serveFallback](https://deno.land/std@0.95.0/http/file_server.ts#L147) and [serverLog](https://deno.land/std@0.95.0/http/file_server.ts#L221) are also unexported. Those last two could also satisfy an API so that the functions in std are a good default but still make it easy to implement a custom logger. The inner [handler](https://deno.land/std@0.95.0/http/file_server.ts#L419) function in the `main` function could also be refactored and exported.

That's just a quick overview, I haven't checked each and every single function and constant in the module, but the point is: I think we can open up this module a little bit to allow more customization in userland.

**Comment by jsjoeio** [comment]
> I think we can open up this module a little bit to allow more customization in userland

Yeah, that would be awesome. I do appreciate how readable the code is so worst case, I can copy and paste and then modify as needed in the meantime.

**Comment by wperron** [comment]
To add to the possible use cases of this proposal; Right now the file server can _almost_ be used as-is for developing front-end application locally. Where it stops becoming sufficient is when using things like JSX or writing source code in TypeScript, which the browser can't parse. Having a file_server that is more open to extension would allow plugging tools like [fresh](https://github.com/lucacasonato/fresh) and turn the default file_server into something that resembles [Vite](https://vitejs.dev/) relatively easily. I think this could strengthen our position in the front-end world and potentially drive adoption.

**Comment by kitsonk** [comment]
There are a lot more limitations with the file server, like it's incomplete version of media types. Plus lots of other features. It was intended as an example application that has grown arms and legs and not something I think we should maintain in std, because it is how deep you go. Personally I would rather us have a few "examples" for Deno if anything and move things like it there. There are quite a few community projects that provide this functionality and better.

Does the Go standard library include a file server?

**Comment by jsjoeio** [comment]
> not something I think we should maintain in std, because it is how deep you go

Definitely a valid point.

> There are quite a few community projects that provide this functionality and better

To play devil's advocate, aren't you biased though since you're the author of @oakserver?

**Comment by kitsonk** [comment]
> To play devil's advocate, aren't you biased though since you're the author of @oakserver?

I could care less about that to be honest. I am a core team member and currently an employee of Deno. My concern is making sure the right focus is there. For example we originally had the `media_types` library as part of `std` only to remove it and I have been maintaining it ever since under the `oakserver` org. I would have no problem taking other core parts out of oak into a "http utils" repo and managing that as a going concern so that we don't encumber or bloat `std`.

**Comment by wperron** [comment]
I agree with you @kitsonk that we should put some barriers on the scope of the file server so that it doesn't become a fully-fledged framework. What I had in mind was more something like [Go's file server](https://pkg.go.dev/net/http#FileServer) in that we can offer some of the building blocks that people can use to build more fully-featured file servers on top of.

I think at this point it might be a good idea to open up a Discussion so that we can refine the scope of the file server going forward and better defined its place in the standard lib. In the meantime, I'd be in favor of getting this issue done; it doesn't add any functionality, it's really just about exposing some of the internals of the file server as it currently is. WDYT?

**Comment by jsjoeio** [comment]
Ah, gotcha. Totally makes sense then.

Super appreciate of you two even considering this, and grateful that the Deno community is so welcoming and friendly.

If there is anything I can do to help with this, please let me know

**Comment by timonson** [comment]
I would love to see `const MEDIA_TYPES` being exported, too. Would there be any downside to exporting a couple of more functions and constants?

**Comment by Dialga** [comment]
I'd also like to use serveDir in my app, should I open a new issue to request it?

**Comment by jespertheend** [comment]
> It was intended as an example application that has grown arms and legs and not something I think we should maintain in std

I think it makes sense for file_server not to grow in too large of a framework. I'm using it for local development only, for production I'd probably want to use something.

That said though, I've reached the point where I need a WebSocket for local development, and I'd like to use the same port for http and the WebSocket, something that could easily have been achieved if `file_server.ts` had exported a few more of its functions.

What I like about Deno is that it comes with all required tools for developing an application, file_server being one of them. I'd be sad to see it removed or only treated as an example. In that case I would most likely not resort to a third party framework, but instead roll my own. Since my use case is a simple one and I want to keep dependencies to a minimum.
