### ISSUE TITLE
test(node): Enable more native node tests

### ISSUE THREAD

**Issue by uki00a** [denoland/deno_std#911]
In #695, the native node test runner has been introduced. Currently, only a very limited amount of tests is enabled. For better compatibility, I think more tests should be enabled.

The following list shows the modules for which native node tests should be enabled:

- [x] assert (_partly_)
- [ ] buffer
- [ ] child_process (_partly_)
- [ ] console
- [ ] constants
- [ ] crypto
- [x] events (_partly_)
- [x] fs (_wip_)
- [ ] module
- [ ] os
- [x] path
- [ ] process
- [x] querystring (_partly_)
- [x] stream
- [ ] string_decoder
- [ ] timers
- [ ] tty
- [x] url (_partly_)
- [x] util (_partly_)

**Comment by uki00a** [comment]
I'm working on `events` :raising_hand_man:

**Comment by wafuwafu13** [comment]
I'm working on `url` 🙋‍♂️

**Comment by wafuwafu13** [comment]
`url` partly done

- [ ]  `test-url-domain-ascii-unicode.js`: TODO because https://github.com/denoland/deno_std/pull/1365#discussion_r724875257
- [x] `test-url-fileurltopath.js`
- [ ] `test-format-invalid-input.js`: Legacy https://nodejs.org/api/url.html#url_url_format_urlobject
- [ ] `test-format-whatwg.js`: Legacy
- [ ] `test-url-format.js`: Legacy
- [ ] `test-url-parse-format.js`: Legacy https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
- [ ] `test-url-parse-invalid-input.js`: Legacy
- [ ] `test-url-parse-query.js`: Legacy
- [x] `test-url-pathtofileurl.js`
- [ ] `test-url-relative.js`: Legacy https://nodejs.org/api/url.html#url_url_resolve_from_to
- [ ] `test-url-urltooptions.js`: TODO because Add in v15.7.0 https://nodejs.org/api/url.html#url_url_urltohttpoptions_url

**Comment by wafuwafu13** [comment]
`querystring` partly done and working on `util`

**Comment by F3n67u** [comment]
I am working on `fs`.

**Comment by wafuwafu13** [comment]
`util` partly done and working on `path`.

**Comment by wafuwafu13** [comment]
`path` done and working on `fs`

**Comment by PolarETech** [comment]
Hi,
I am working on `fs.ReadStream` (#2653) and `child_process.exec`.

**Comment by PolarETech** [comment]
`fs.ReadStream` and `child_process.exec` are partly done.
I'm starting on `fs.WriteStream`.

**Comment by kt3k** [comment]
This will be tracked in `tools/node_compat/TODO.md` of denoland/deno repo. https://github.com/denoland/deno/pull/18290/files#diff-66a13180ca921c746469f8f0bf6ec0cafab925839d65fdca6379866c4bb7be40
