### ISSUE TITLE
[feature request] assertEquals multiline string diffs

### ISSUE THREAD

**Issue by andykais** [denoland/deno_std#929]
currently `assertEquals` will pretty print js object differences 
![screenshot(616)](https://user-images.githubusercontent.com/6627147/119001162-baac1600-b959-11eb-9211-f9b236a0c75d.png)

but will show multiline string diffs as a single blob 
![screenshot(617)](https://user-images.githubusercontent.com/6627147/119001197-c566ab00-b959-11eb-9044-49196a742cfd.png)
The actual diff here is pretty much unreadible so I often end up writing the changes to a file and using `git diff` or the `diff` command to see the actual changes.

It would be great if assertEquals could show multiline string diffs in a similar manner to `git diff`

**Comment by lowlighter** [comment]
Do you mean something like `git diff --word-diff` ?

**Comment by andykais** [comment]
@lowlighter sure, but even a normal `git diff` would be an improvement. That is a multiple line string comparison, but it reads as a single line comparison

**Comment by ebebbington** [comment]
I too think this would be nice to have, there's plenty of times where im wanting to assert a very large string ie help output from a cli - i have to just sift through every character and compare if the first line in the expected ends with the same character as the actual, then the same for line 2, and so on 😆 

Granted i'm the on with massive strings so i brought it upon myself, but would be nice to have multiline string diffs (eg not escaping newlines or colour encoding)

**Comment by lowlighter** [comment]
So I made a prototype for both multi-lines/words diffs which render like below:

![image](https://user-images.githubusercontent.com/22963968/120538352-b31f4f00-c3e6-11eb-98b1-44b7315735c2.png)
![image](https://user-images.githubusercontent.com/22963968/120538377-b87c9980-c3e6-11eb-9544-17a2882b9771.png)

Basically if both operands are string, a custom string tokenizer is called before entering `diff()` function.

I'm not sure how to auto-switch from multi-lines diff to word-diff yet though 🤔 
I think words is more readable when few words are edited so maybe a threshold to switch to multi-lines based on number of words edited would be the best.

If this looks fines, I'll finish it and submit it for review 👍 

@ebebbington Not escaping colours seems a bit tricky, since the diff renderer currently uses colors, not sure what would be the right way to do this
