### ISSUE TITLE
Add CRC32C API

### ISSUE THREAD

**Issue by mattbishop** [denoland/deno_std#972]
I have been using a node wrapper of a rust CRC32C implementation: https://github.com/napi-rs/node-rs/tree/main/packages/crc32

This capability makes sense to be in the Deno std lib because it takes advantage of CPU-specific hardware instructions to calculate CRC values. It supports a wide variety of architectures.

**Comment by FujiHaruka** [comment]
I took a glance at hash/_wasm.

We can add a hash algorithm in rust by adding to this list in lib.rs.

https://github.com/denoland/deno_std/blob/f4496b78ef3874bdc06f6a6de10cdadb97b6f2bb/hash/_wasm/src/lib.rs

All hash structs here implement [Digest](https://crates.io/crates/digest) traits.

However, [crc32fast](https://crates.io/crates/crc32fast), which is the most popular crc32 library in crates.io, doesn't implement Digest traits. We have something to do in order to import crc32fast to _wasm. (But I don't know much about rust).

**Comment by jeremyBanks** [comment]
> This capability makes sense to be in the Deno std lib because it takes advantage of CPU-specific hardware instructions to calculate CRC values. 

`deno_std` isn't able to take advantage of CPU-specific hardware instructions directly; it's implemented in TypeScript(/JavaScript/WASM). To take full advantage of something it would need to be added to the Deno runtime directly. However, I think WASM SIMD is now supported in Deno's v8, so a WASM implementation might be able to perform competitively.

> We can add a hash algorithm in rust by adding to this list in lib.rs.

Sorry, I probably should have left a note in that directory, but `hash/_wasm` is deprecated and being replaced with `hash/crypto`/`hash/_wasm_crypto` (see #1025). The new implementation doesn't use the Digest trait, 
just a bunch of `match` statements (see https://github.com/denoland/deno_std/blob/main/_wasm_crypto/src/digest.rs), so if we wanted to add CRC support to that interface it should be pretty straightforward.

**Comment by iuioiua** [comment]
I'm going to close this as I haven't seen sufficient demand for this. If anyone is still strongly for having this functionality, please feel free to re-open this issue. Either way, thank you for your input, guys.
